# -*- coding: utf-8 -*-
"""第四批補譯：P5 SSL 實測後改寫的註解與說明（18 條 × 17 語言）。

多數是 tt 模板被拆成的片段（「 秒」「，範圍 0–65535」這種），
單獨看沒有意義，必須照它們在句子裡的位置翻，否則接起來會不通順。
"""
import io
import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEYS = json.load(io.open(os.path.join(ROOT, 'i18n', 'tr10-source.json'), encoding='utf-8'))
OUT = os.path.join(ROOT, 'i18n', 'tr10')

T = {
 'en-US': [
  "0 = no verification at all; 1 = verify the server (a trusted CA certificate must already be in the module's UFS); 2 = mutual server and client verification (a client cert and private key are also needed when the peer asks for them). Manual §4 is explicit: with seclevel 1 or 2 you must first upload a certificate with AT+QFUPL. ⚠ The old note here claimed \"this tool cannot send a certificate so it always fails\" — that was wrong. PEM is plain ASCII, and on 2026-08-07 the P5 run uploaded a 1939-byte ISRG Root X1 and passed verification. There is no upload button in the UI yet, so drive AT+QFUPL through its two-stage flow by hand. ⚠ Also note that sni defaults to 0: a server hosting several domains on one IP (badssl.com does) hands you a mismatched certificate when no SNI is sent, and verification fails with 566.",
  "After the module answers >, it sends only once it has counted the exact number of bytes you declared. If the length is wrong or you abandon it midway, the AT port stays in data mode and swallows everything you type next — send ESC (0x1B) with the raw-byte button on the Hardware page to get out; you do not have to close the connection or restart the module. The data really goes over the network and costs traffic.",
  "Queries only the connection with clientID {0}, reporting remote address and port, local port, state code, PDP and SSL context IDs, and the AT port in use.",
  "Sends exactly {1} bytes on clientID {0}: after the module answers >, it transmits only once exactly {2} bytes have arrived, ",
  "Reads at most {1} bytes from the receive buffer of clientID {0} (range 0–1500, default 1500); ",
  "Connects to {2}:{3} over PDP context {0} and SSL context {1}; this connection's clientID is {4}; ",
  "Closes clientID {0} with close_timeout set to {1}",
  "Closes the SSL connection on clientID {0}; with no timeout parameter the default of 10 seconds applies; ",
  " seconds",
  ". The immediate OK only means the command was accepted — success or failure arrives in the +QSSLOPEN URC",
  "no Ctrl+Z needed. The per-call limit is 1460; out-of-range values return ERROR",
  "the module releases the SSL context only after every connection on it is closed",
  "trailing 0 = buffer mode, you fetch the data yourself with AT+QSSLRECV",
  "trailing 1 = direct push, incoming data comes straight out in a +QSSLURC together with its content, no separate read",
  "trailing 2 = transparent mode, the AT port becomes the data channel",
  "reading +QSSLRECV: 0 means the buffer is empty; only buffer mode needs this command",
  ", range 0–65535",
  " = close immediately without waiting"],
 'ja-JP': [
  "0＝検証を一切行わない、1＝サーバーを検証（信頼する CA 証明書があらかじめモジュールの UFS に必要）、2＝サーバーとクライアントの相互検証（相手が要求する場合はクライアント証明書と秘密鍵も必要）。マニュアル §4 に明記のとおり、seclevel を 1 か 2 にするなら先に AT+QFUPL で証明書をアップロードする必要があります。⚠ 以前ここに書いていた「本ツールでは証明書を送れないので必ず失敗する」は誤りです —— PEM は純粋な ASCII で、2026-08-07 の P5 実測では 1939 バイトの ISRG Root X1 をアップロードして検証を通しました。UI にアップロードボタンはまだないので、AT+QFUPL の 2 段階フローを手動で実行してください。⚠ また sni の工場出荷値は 0 です：1 つの IP に複数ドメインを載せたサーバー（badssl.com がそう）では、SNI を送らないと一致しない証明書が返り、検証は 566 で必ず失敗します。",
  "モジュールが > を返したあと、宣言した長さちょうどのバイト数を数え終えてから送信します。長さを間違えたり途中でやめたりすると、AT ポートがデータモードに留まって以降の入力を飲み込みます —— Hardware ページの生バイト送信ボタンで ESC（0x1B）を送れば抜けられます。接続を閉じたりモジュールを再起動したりする必要はありません。データは実際にネットワークへ出るので通信量が発生します。",
  "clientID {0} のこの 1 本だけを照会し、リモートのアドレスとポート、ローカルポート、状態コード、PDP と SSL の context ID、使用中の AT ポートを返します。",
  "clientID {0} へ固定長 {1} バイトを送信：モジュールが > を返したあと、ちょうど {2} バイト受け取った時点で初めて送出されます。",
  "clientID {0} の受信バッファから最大 {1} バイト読み出します（範囲 0–1500、既定 1500）。",
  "PDP context {0}、SSL context {1} を使って {2}:{3} へ接続します。この接続の clientID は {4} です。",
  "clientID {0} を閉じ、close_timeout を {1} に設定します",
  "clientID {0} の SSL 接続を閉じます。タイムアウト引数を付けなければ既定の 10 秒が使われます。",
  " 秒",
  "。すぐ返る OK はコマンドを受け付けた意味だけで、成否は +QSSLOPEN URC で届きます",
  "Ctrl+Z は不要です。1 回の上限は 1460 で、範囲外なら ERROR が返ります",
  "同じ SSL context 上の接続がすべて閉じられて初めて、モジュールはその context を解放します",
  "末尾 0＝バッファモード。データは自分で AT+QSSLRECV を叩いて取り出します",
  "末尾 1＝ダイレクトプッシュ。受信データは +QSSLURC が中身ごとそのまま吐き出すので、別途読み出す必要はありません",
  "末尾 2＝透過モード。AT ポートがそのままデータ通路になります",
  "+QSSLRECV: 0 が返ればバッファは空です。このコマンドが要るのはバッファモードだけです",
  "、範囲 0–65535",
  "＝待たずに即座に閉じる"],
 'de-DE': [
  "0 = überhaupt keine Prüfung; 1 = Server prüfen (ein vertrauenswürdiges CA-Zertifikat muss bereits im UFS des Moduls liegen); 2 = gegenseitige Prüfung von Server und Client (auf Verlangen der Gegenstelle sind zusätzlich Client-Zertifikat und privater Schlüssel nötig). Handbuch §4 sagt es deutlich: bei seclevel 1 oder 2 muss zuerst ein Zertifikat mit AT+QFUPL hochgeladen werden. ⚠ Der frühere Hinweis „dieses Werkzeug kann kein Zertifikat senden, also scheitert es immer“ war falsch — PEM ist reines ASCII, und am 2026-08-07 hat der P5-Lauf ein 1939 Byte großes ISRG Root X1 hochgeladen und die Prüfung bestanden. Eine Upload-Schaltfläche gibt es in der Oberfläche noch nicht, AT+QFUPL muss also von Hand durch seinen zweistufigen Ablauf geführt werden. ⚠ Beachten Sie außerdem: sni steht ab Werk auf 0. Ein Server mit mehreren Domains auf einer IP (badssl.com ist so einer) liefert ohne SNI ein nicht passendes Zertifikat, und die Prüfung scheitert mit 566.",
  "Nachdem das Modul mit > geantwortet hat, sendet es erst, wenn es genau die angegebene Anzahl Bytes gezählt hat. Stimmt die Länge nicht oder brechen Sie mittendrin ab, bleibt der AT-Port im Datenmodus und verschluckt alles Weitere — senden Sie ESC (0x1B) mit der Rohbyte-Schaltfläche auf der Hardware-Seite, um herauszukommen; Verbindung schließen oder Modul neu starten ist nicht nötig. Die Daten gehen wirklich ins Netz und kosten Datenvolumen.",
  "Fragt nur die Verbindung mit clientID {0} ab und meldet Gegenstellenadresse und -port, lokalen Port, Zustandscode, PDP- und SSL-Context-ID sowie den verwendeten AT-Port.",
  "Sendet auf clientID {0} genau {1} Bytes: nachdem das Modul mit > geantwortet hat, überträgt es erst, wenn exakt {2} Bytes eingetroffen sind, ",
  "Liest höchstens {1} Bytes aus dem Empfangspuffer von clientID {0} (Bereich 0–1500, Vorgabe 1500); ",
  "Verbindet über PDP-Context {0} und SSL-Context {1} zu {2}:{3}; die clientID dieser Verbindung ist {4}; ",
  "Schließt clientID {0} und setzt close_timeout auf {1}",
  "Schließt die SSL-Verbindung auf clientID {0}; ohne Timeout-Parameter gilt die Vorgabe von 10 Sekunden; ",
  " Sekunden",
  ". Das sofortige OK bedeutet nur, dass der Befehl angenommen wurde — Erfolg oder Misserfolg kommt in der URC +QSSLOPEN",
  "kein Ctrl+Z nötig. Die Obergrenze je Aufruf ist 1460; Werte außerhalb des Bereichs liefern ERROR",
  "das Modul gibt den SSL-Context erst frei, wenn alle Verbindungen darauf geschlossen sind",
  "abschließende 0 = Puffermodus, die Daten holen Sie selbst mit AT+QSSLRECV ab",
  "abschließende 1 = Direct Push, eingehende Daten kommen samt Inhalt direkt in einer +QSSLURC heraus, kein separates Lesen",
  "abschließende 2 = transparenter Modus, der AT-Port wird zum Datenkanal",
  "ein +QSSLRECV: 0 bedeutet, der Puffer ist leer; nur der Puffermodus braucht diesen Befehl",
  ", Bereich 0–65535",
  " = sofort schließen, ohne zu warten"],
 'fr-FR': [
  "0 = aucune vérification ; 1 = vérifier le serveur (un certificat CA de confiance doit déjà se trouver dans l'UFS du module) ; 2 = vérification mutuelle serveur et client (un certificat client et une clé privée sont également nécessaires si le pair les réclame). Le manuel §4 est formel : avec seclevel 1 ou 2, il faut d'abord téléverser un certificat par AT+QFUPL. ⚠ L'ancienne note « cet outil ne peut pas envoyer de certificat, l'échec est donc certain » était fausse — le PEM est du pur ASCII, et le 2026-08-07 la campagne P5 a téléversé un ISRG Root X1 de 1939 octets et passé la vérification. Il n'existe pas encore de bouton de téléversement dans l'interface : il faut dérouler à la main le flux en deux temps d'AT+QFUPL. ⚠ Notez aussi que sni vaut 0 en sortie d'usine : un serveur hébergeant plusieurs domaines sur une même IP (c'est le cas de badssl.com) renvoie un certificat non concordant si le SNI n'est pas envoyé, et la vérification échoue avec 566.",
  "Après que le module a répondu >, il n'émet qu'une fois comptés exactement les octets annoncés. Si la longueur est fausse ou que vous abandonnez en cours de route, le port AT reste en mode données et avale tout ce que vous tapez ensuite — envoyez ESC (0x1B) avec le bouton d'octet brut de la page Hardware pour vous en sortir ; inutile de fermer la connexion ou de redémarrer le module. Les données partent réellement sur le réseau et consomment du trafic.",
  "N'interroge que la connexion de clientID {0}, en indiquant l'adresse et le port distants, le port local, le code d'état, les identifiants de contexte PDP et SSL, ainsi que le port AT utilisé.",
  "Envoie exactement {1} octets sur le clientID {0} : après le > du module, l'émission n'a lieu qu'une fois exactement {2} octets reçus, ",
  "Lit au plus {1} octets dans le tampon de réception du clientID {0} (plage 0–1500, défaut 1500) ; ",
  "Se connecte à {2}:{3} via le contexte PDP {0} et le contexte SSL {1} ; le clientID de cette connexion est {4} ; ",
  "Ferme le clientID {0} en réglant close_timeout sur {1}",
  "Ferme la connexion SSL du clientID {0} ; sans paramètre de délai, la valeur par défaut de 10 secondes s'applique ; ",
  " secondes",
  ". Le OK immédiat signifie seulement que la commande a été acceptée — la réussite ou l'échec arrive dans l'URC +QSSLOPEN",
  "pas besoin de Ctrl+Z. La limite par appel est de 1460 ; hors plage, la réponse est ERROR",
  "le module ne libère le contexte SSL qu'une fois toutes ses connexions fermées",
  "0 final = mode tampon, vous récupérez vous-même les données par AT+QSSLRECV",
  "1 final = envoi direct, les données reçues ressortent telles quelles dans un +QSSLURC avec leur contenu, sans lecture séparée",
  "2 final = mode transparent, le port AT devient le canal de données",
  "recevoir +QSSLRECV: 0 signifie que le tampon est vide ; seul le mode tampon a besoin de cette commande",
  ", plage 0–65535",
  " = fermeture immédiate sans attente"],
 'es-ES': [
  "0 = sin verificación alguna; 1 = verificar el servidor (en el UFS del módulo debe haber ya un certificado CA de confianza); 2 = verificación mutua de servidor y cliente (si el otro extremo lo pide, hacen falta además certificado de cliente y clave privada). El manual §4 es explícito: con seclevel 1 o 2 hay que subir antes un certificado con AT+QFUPL. ⚠ La nota anterior, «esta herramienta no puede enviar certificados, así que siempre falla», era incorrecta: el PEM es ASCII puro y el 2026-08-07 la tanda P5 subió un ISRG Root X1 de 1939 bytes y superó la verificación. Todavía no hay botón de subida en la interfaz, así que hay que recorrer a mano el flujo en dos pasos de AT+QFUPL. ⚠ Ten en cuenta también que sni viene de fábrica a 0: un servidor con varios dominios en una misma IP (badssl.com lo es) devuelve un certificado que no concuerda si no se envía SNI, y la verificación falla con 566.",
  "Después de que el módulo responda >, no envía hasta haber contado exactamente los bytes declarados. Si la longitud está mal o lo abandonas a medias, el puerto AT se queda en modo datos y se traga todo lo que escribas después: envía ESC (0x1B) con el botón de byte en crudo de la página Hardware para salir; no hace falta cerrar la conexión ni reiniciar el módulo. Los datos salen de verdad a la red y consumen tráfico.",
  "Consulta solo la conexión con clientID {0}, e informa de la dirección y el puerto remotos, el puerto local, el código de estado, los identificadores de contexto PDP y SSL, y el puerto AT en uso.",
  "Envía exactamente {1} bytes por el clientID {0}: tras el > del módulo, no transmite hasta que hayan llegado justo {2} bytes, ",
  "Lee como mucho {1} bytes del búfer de recepción del clientID {0} (rango 0–1500, predeterminado 1500); ",
  "Conecta con {2}:{3} usando el contexto PDP {0} y el contexto SSL {1}; el clientID de esta conexión es {4}; ",
  "Cierra el clientID {0} y fija close_timeout en {1}",
  "Cierra la conexión SSL del clientID {0}; sin parámetro de tiempo de espera se aplica el valor predeterminado de 10 segundos; ",
  " segundos",
  ". El OK inmediato solo significa que se aceptó el comando: el éxito o el fallo llega en la URC +QSSLOPEN",
  "no hace falta Ctrl+Z. El límite por llamada es 1460; fuera de rango se responde ERROR",
  "el módulo no libera el contexto SSL hasta que se cierran todas sus conexiones",
  "el 0 final = modo búfer, los datos los recoges tú con AT+QSSLRECV",
  "el 1 final = envío directo, los datos recibidos salen tal cual en un +QSSLURC junto con su contenido, sin lectura aparte",
  "el 2 final = modo transparente, el puerto AT pasa a ser el canal de datos",
  "recibir +QSSLRECV: 0 significa que el búfer está vacío; solo el modo búfer necesita este comando",
  ", rango 0–65535",
  " = cerrar de inmediato sin esperar"],
 'pt-PT': [
  "0 = sem qualquer verificação; 1 = verificar o servidor (o UFS do módulo tem de ter já um certificado CA de confiança); 2 = verificação mútua de servidor e cliente (se a outra ponta pedir, são precisos também certificado de cliente e chave privada). O manual §4 é explícito: com seclevel 1 ou 2 é preciso carregar antes um certificado com AT+QFUPL. ⚠ A nota anterior, «esta ferramenta não consegue enviar certificados, por isso falha sempre», estava errada — o PEM é ASCII puro e, a 2026-08-07, a campanha P5 carregou um ISRG Root X1 de 1939 bytes e passou a verificação. Ainda não há botão de carregamento na interface, por isso é preciso percorrer à mão o fluxo em duas fases do AT+QFUPL. ⚠ Note também que o sni vem de fábrica a 0: um servidor com vários domínios no mesmo IP (o badssl.com é um deles) devolve um certificado que não corresponde se não for enviado SNI, e a verificação falha com 566.",
  "Depois de o módulo responder >, só envia quando tiver contado exatamente os bytes declarados. Se o comprimento estiver errado ou desistir a meio, a porta AT fica em modo de dados e engole tudo o que escrever a seguir — envie ESC (0x1B) com o botão de byte em bruto da página Hardware para sair; não é preciso fechar a ligação nem reiniciar o módulo. Os dados saem mesmo para a rede e consomem tráfego.",
  "Consulta apenas a ligação com clientID {0}, indicando endereço e porta remotos, porta local, código de estado, identificadores de contexto PDP e SSL, e a porta AT em uso.",
  "Envia exatamente {1} bytes no clientID {0}: depois do > do módulo, só transmite quando tiverem chegado precisamente {2} bytes, ",
  "Lê no máximo {1} bytes do buffer de receção do clientID {0} (intervalo 0–1500, predefinição 1500); ",
  "Liga a {2}:{3} através do contexto PDP {0} e do contexto SSL {1}; o clientID desta ligação é {4}; ",
  "Fecha o clientID {0} e define close_timeout como {1}",
  "Fecha a ligação SSL do clientID {0}; sem parâmetro de tempo limite aplica-se a predefinição de 10 segundos; ",
  " segundos",
  ". O OK imediato significa apenas que o comando foi aceite — o êxito ou a falha chega na URC +QSSLOPEN",
  "não é preciso Ctrl+Z. O limite por chamada é 1460; fora do intervalo responde ERROR",
  "o módulo só liberta o contexto SSL depois de fechadas todas as ligações nele",
  "o 0 final = modo buffer, os dados é você que os vai buscar com AT+QSSLRECV",
  "o 1 final = envio direto, os dados recebidos saem tal e qual num +QSSLURC juntamente com o conteúdo, sem leitura à parte",
  "o 2 final = modo transparente, a porta AT passa a ser o canal de dados",
  "receber +QSSLRECV: 0 significa que o buffer está vazio; só o modo buffer precisa deste comando",
  ", intervalo 0–65535",
  " = fechar de imediato sem esperar"],
 'it-IT': [
  "0 = nessuna verifica; 1 = verifica del server (nell'UFS del modulo deve già esserci un certificato CA attendibile); 2 = verifica reciproca di server e client (se la controparte lo richiede servono anche certificato client e chiave privata). Il manuale §4 è esplicito: con seclevel 1 o 2 occorre prima caricare un certificato con AT+QFUPL. ⚠ La nota precedente, «questo strumento non può inviare certificati, quindi fallisce sempre», era sbagliata: il PEM è ASCII puro e il 2026-08-07 la sessione P5 ha caricato un ISRG Root X1 da 1939 byte superando la verifica. Nell'interfaccia non c'è ancora un pulsante di caricamento, quindi il flusso in due fasi di AT+QFUPL va eseguito a mano. ⚠ Nota inoltre che sni è 0 di fabbrica: un server con più domini sullo stesso IP (badssl.com lo è) restituisce un certificato non corrispondente se non si invia l'SNI, e la verifica fallisce con 566.",
  "Dopo che il modulo risponde >, invia solo quando ha contato esattamente i byte dichiarati. Se la lunghezza è sbagliata o abbandoni a metà, la porta AT resta in modalità dati e ingoia tutto ciò che digiti dopo: manda ESC (0x1B) con il pulsante byte grezzo della pagina Hardware per uscirne; non serve chiudere la connessione né riavviare il modulo. I dati escono davvero in rete e consumano traffico.",
  "Interroga solo la connessione con clientID {0}, riportando indirizzo e porta remoti, porta locale, codice di stato, ID dei contesti PDP e SSL e la porta AT in uso.",
  "Invia esattamente {1} byte sul clientID {0}: dopo il > del modulo, trasmette solo quando sono arrivati esattamente {2} byte, ",
  "Legge al massimo {1} byte dal buffer di ricezione del clientID {0} (intervallo 0–1500, predefinito 1500); ",
  "Si collega a {2}:{3} tramite il contesto PDP {0} e il contesto SSL {1}; il clientID di questa connessione è {4}; ",
  "Chiude il clientID {0} impostando close_timeout a {1}",
  "Chiude la connessione SSL sul clientID {0}; senza parametro di timeout vale il predefinito di 10 secondi; ",
  " secondi",
  ". L'OK immediato significa solo che il comando è stato accettato: l'esito arriva nella URC +QSSLOPEN",
  "non serve Ctrl+Z. Il limite per chiamata è 1460; fuori intervallo risponde ERROR",
  "il modulo libera il contesto SSL solo dopo che tutte le sue connessioni sono chiuse",
  "lo 0 finale = modalità buffer, i dati li recuperi tu con AT+QSSLRECV",
  "l'1 finale = push diretto, i dati ricevuti escono così come sono in una +QSSLURC insieme al contenuto, senza lettura separata",
  "il 2 finale = modalità trasparente, la porta AT diventa il canale dati",
  "ricevere +QSSLRECV: 0 significa che il buffer è vuoto; solo la modalità buffer richiede questo comando",
  ", intervallo 0–65535",
  " = chiusura immediata senza attesa"],
 'ru-RU': [
  "0 — никакой проверки; 1 — проверять сервер (доверенный CA-сертификат уже должен лежать в UFS модуля); 2 — взаимная проверка сервера и клиента (если того требует другая сторона, нужны ещё клиентский сертификат и закрытый ключ). Руководство §4 говорит прямо: при seclevel 1 или 2 сначала надо загрузить сертификат командой AT+QFUPL. ⚠ Прежняя пометка «этот инструмент не умеет отправлять сертификаты, поэтому всегда провал» была неверной: PEM — чистый ASCII, и 2026-08-07 в ходе P5 был загружен ISRG Root X1 размером 1939 байт, проверка прошла. Кнопки загрузки в интерфейсе пока нет, поэтому двухэтапный обмен AT+QFUPL приходится проводить вручную. ⚠ Учтите также, что sni по умолчанию равен 0: сервер с несколькими доменами на одном IP (badssl.com именно такой) без SNI отдаёт несоответствующий сертификат, и проверка падает с кодом 566.",
  "После того как модуль ответит >, он отправит данные только досчитав ровно столько байт, сколько вы объявили. Если длина указана неверно или вы бросили на полпути, AT-порт останется в режиме данных и будет проглатывать всё, что вы наберёте дальше, — отправьте ESC (0x1B) кнопкой сырого байта на странице Hardware, и вы выйдете; закрывать соединение или перезапускать модуль не нужно. Данные реально уходят в сеть и расходуют трафик.",
  "Запрашивает только соединение с clientID {0} и сообщает удалённый адрес и порт, локальный порт, код состояния, идентификаторы контекстов PDP и SSL, а также используемый AT-порт.",
  "Отправляет по clientID {0} ровно {1} байт: после ответа > модуль передаёт лишь тогда, когда получит ровно {2} байт, ",
  "Читает не более {1} байт из приёмного буфера clientID {0} (диапазон 0–1500, по умолчанию 1500); ",
  "Подключается к {2}:{3} через контекст PDP {0} и контекст SSL {1}; clientID этого соединения — {4}; ",
  "Закрывает clientID {0}, задавая close_timeout равным {1}",
  "Закрывает SSL-соединение на clientID {0}; без параметра тайм-аута действует значение по умолчанию 10 секунд; ",
  " с",
  ". Мгновенный OK означает лишь то, что команда принята, — успех или неудача придут в URC +QSSLOPEN",
  "Ctrl+Z не нужен. Предел за один вызов — 1460; значение вне диапазона даёт ERROR",
  "модуль освобождает SSL-контекст только после закрытия всех соединений на нём",
  "завершающий 0 — буферный режим, данные вы забираете сами командой AT+QSSLRECV",
  "завершающая 1 — прямая выдача: принятые данные выходят прямо в +QSSLURC вместе с содержимым, отдельно читать не надо",
  "завершающая 2 — прозрачный режим, AT-порт становится каналом данных",
  "ответ +QSSLRECV: 0 означает, что буфер пуст; эта команда нужна только в буферном режиме",
  ", диапазон 0–65535",
  " — закрыть немедленно, не дожидаясь"],
 'vi-VN': [
  "0 = không kiểm tra gì cả; 1 = xác thực máy chủ (trong UFS của module phải có sẵn chứng chỉ CA tin cậy); 2 = xác thực hai chiều máy chủ và máy khách (nếu đầu kia yêu cầu thì còn cần chứng chỉ máy khách và khoá riêng). Sổ tay §4 nói rõ: đặt seclevel 1 hoặc 2 thì trước hết phải nạp chứng chỉ bằng AT+QFUPL. ⚠ Câu ghi chú cũ «công cụ này không gửi được chứng chỉ nên chắc chắn hỏng» là sai — PEM là ASCII thuần, và ngày 2026-08-07 đợt P5 đã nạp thành công ISRG Root X1 dài 1939 byte và qua được khâu xác thực. Giao diện chưa có nút nạp, nên phải tự chạy quy trình hai bước của AT+QFUPL. ⚠ Cũng lưu ý sni mặc định xuất xưởng là 0: máy chủ đặt nhiều tên miền trên cùng một IP (badssl.com chính là vậy) sẽ trả về chứng chỉ không khớp nếu không gửi SNI, và xác thực chắc chắn hỏng với mã 566.",
  "Sau khi module trả về >, nó chỉ phát đi khi đã đếm đủ đúng số byte bạn khai báo. Nếu tính sai độ dài hoặc bỏ dở giữa chừng, cổng AT sẽ kẹt ở chế độ dữ liệu và nuốt hết mọi thứ bạn gõ tiếp — hãy gửi ESC (0x1B) bằng nút byte thô ở trang Hardware là thoát được, không cần đóng kết nối hay khởi động lại module. Dữ liệu thật sự đi ra mạng và tốn lưu lượng.",
  "Chỉ truy vấn kết nối mang clientID {0}, báo về địa chỉ và cổng phía xa, cổng nội bộ, mã trạng thái, ID của PDP context và SSL context, cùng cổng AT đang dùng.",
  "Gửi đúng {1} byte trên clientID {0}: sau khi module trả về >, nó chỉ phát đi khi đã nhận đủ đúng {2} byte, ",
  "Đọc tối đa {1} byte từ bộ đệm nhận của clientID {0} (khoảng 0–1500, mặc định 1500); ",
  "Kết nối tới {2}:{3} qua PDP context {0} và SSL context {1}; clientID của kết nối này là {4}; ",
  "Đóng clientID {0} và đặt close_timeout thành {1}",
  "Đóng kết nối SSL trên clientID {0}; không kèm tham số thời gian chờ thì lấy mặc định 10 giây; ",
  " giây",
  ". Chữ OK trả về ngay chỉ có nghĩa lệnh đã được nhận — thành bại nằm ở URC +QSSLOPEN",
  "không cần Ctrl+Z. Giới hạn mỗi lần là 1460; ngoài khoảng sẽ trả về ERROR",
  "module chỉ giải phóng SSL context sau khi mọi kết nối trên nó đã đóng",
  "số 0 ở cuối = chế độ đệm, dữ liệu bạn tự lấy bằng AT+QSSLRECV",
  "số 1 ở cuối = đẩy thẳng, dữ liệu nhận được ra luôn trong +QSSLURC kèm nội dung, không phải đọc riêng",
  "số 2 ở cuối = chế độ trong suốt, cổng AT trở thành kênh dữ liệu",
  "đọc ra +QSSLRECV: 0 nghĩa là bộ đệm đã rỗng; chỉ chế độ đệm mới cần lệnh này",
  ", khoảng 0–65535",
  " = đóng ngay không chờ"],
 'id-ID': [
  "0 = tanpa verifikasi sama sekali; 1 = verifikasi server (sertifikat CA tepercaya harus sudah ada di UFS modul); 2 = verifikasi dua arah server dan klien (bila pihak seberang memintanya, perlu juga sertifikat klien dan kunci privat). Manual §4 menyatakan tegas: dengan seclevel 1 atau 2 sertifikat harus diunggah lebih dulu memakai AT+QFUPL. ⚠ Catatan lama «alat ini tidak bisa mengirim sertifikat sehingga pasti gagal» itu keliru — PEM adalah ASCII murni, dan pada 2026-08-07 rangkaian P5 berhasil mengunggah ISRG Root X1 sebesar 1939 byte serta lolos verifikasi. Belum ada tombol unggah di antarmuka, jadi alur dua tahap AT+QFUPL harus dijalankan manual. ⚠ Perhatikan juga sni bawaan pabrik bernilai 0: server yang menaruh banyak domain di satu IP (badssl.com begitu) akan mengembalikan sertifikat yang tidak cocok bila SNI tidak dikirim, dan verifikasi pasti gagal dengan 566.",
  "Setelah modul menjawab >, ia baru mengirim ketika sudah menghitung persis sebanyak byte yang Anda nyatakan. Kalau panjangnya salah atau Anda batalkan di tengah jalan, port AT tetap di mode data dan menelan semua yang Anda ketik berikutnya — kirim ESC (0x1B) dengan tombol byte mentah di halaman Hardware untuk keluar; tidak perlu menutup koneksi atau memulai ulang modul. Datanya benar-benar keluar ke jaringan dan memakan kuota.",
  "Hanya menanyakan koneksi dengan clientID {0}, melaporkan alamat dan port jarak jauh, port lokal, kode status, ID context PDP dan SSL, serta port AT yang dipakai.",
  "Mengirim tepat {1} byte pada clientID {0}: setelah modul menjawab >, ia baru memancarkan ketika persis {2} byte sudah masuk, ",
  "Membaca paling banyak {1} byte dari buffer penerimaan clientID {0} (rentang 0–1500, bawaan 1500); ",
  "Menyambung ke {2}:{3} lewat context PDP {0} dan context SSL {1}; clientID koneksi ini adalah {4}; ",
  "Menutup clientID {0} dan menyetel close_timeout menjadi {1}",
  "Menutup koneksi SSL pada clientID {0}; tanpa parameter batas waktu berlaku bawaan 10 detik; ",
  " detik",
  ". OK yang langsung muncul hanya berarti perintah diterima — berhasil atau gagalnya datang di URC +QSSLOPEN",
  "tidak perlu Ctrl+Z. Batas per panggilan adalah 1460; di luar rentang dijawab ERROR",
  "modul baru melepas context SSL setelah semua koneksi di atasnya ditutup",
  "angka 0 di akhir = mode buffer, datanya Anda ambil sendiri dengan AT+QSSLRECV",
  "angka 1 di akhir = dorong langsung, data masuk keluar apa adanya di +QSSLURC beserta isinya, tanpa pembacaan terpisah",
  "angka 2 di akhir = mode transparan, port AT menjadi kanal data",
  "membaca +QSSLRECV: 0 berarti buffer sudah kosong; hanya mode buffer yang membutuhkan perintah ini",
  ", rentang 0–65535",
  " = tutup seketika tanpa menunggu"],
 'ms-MY': [
  "0 = tiada pengesahan langsung; 1 = sahkan pelayan (sijil CA dipercayai mesti sudah ada dalam UFS modul); 2 = pengesahan dua hala pelayan dan klien (jika pihak seberang memintanya, sijil klien dan kunci persendirian turut diperlukan). Manual §4 menyatakan dengan jelas: dengan seclevel 1 atau 2, sijil mesti dimuat naik dahulu menggunakan AT+QFUPL. ⚠ Nota lama «alat ini tidak boleh menghantar sijil jadi pasti gagal» adalah salah — PEM ialah ASCII tulen, dan pada 2026-08-07 pusingan P5 berjaya memuat naik ISRG Root X1 sebesar 1939 bait serta lulus pengesahan. Belum ada butang muat naik pada antara muka, jadi aliran dua peringkat AT+QFUPL perlu dijalankan secara manual. ⚠ Perhatikan juga sni lalai kilang ialah 0: pelayan yang meletakkan banyak domain pada satu IP (badssl.com begitu) akan memulangkan sijil yang tidak sepadan jika SNI tidak dihantar, dan pengesahan pasti gagal dengan 566.",
  "Selepas modul membalas >, ia hanya menghantar apabila sudah mengira tepat bilangan bait yang anda isytiharkan. Jika panjangnya salah atau anda batalkan di pertengahan, port AT akan kekal dalam mod data dan menelan segala yang anda taip selepas itu — hantar ESC (0x1B) dengan butang bait mentah pada halaman Hardware untuk keluar; tidak perlu menutup sambungan atau memulakan semula modul. Data benar-benar keluar ke rangkaian dan memakan kuota.",
  "Hanya menanyakan sambungan dengan clientID {0}, melaporkan alamat dan port jauh, port tempatan, kod keadaan, ID context PDP dan SSL, serta port AT yang digunakan.",
  "Menghantar tepat {1} bait pada clientID {0}: selepas modul membalas >, ia hanya memancar apabila tepat {2} bait telah tiba, ",
  "Membaca paling banyak {1} bait daripada penimbal penerimaan clientID {0} (julat 0–1500, lalai 1500); ",
  "Menyambung ke {2}:{3} melalui context PDP {0} dan context SSL {1}; clientID sambungan ini ialah {4}; ",
  "Menutup clientID {0} dan menetapkan close_timeout kepada {1}",
  "Menutup sambungan SSL pada clientID {0}; tanpa parameter had masa, lalai 10 saat digunakan; ",
  " saat",
  ". OK yang muncul serta-merta hanya bermakna arahan diterima — berjaya atau gagal datang dalam URC +QSSLOPEN",
  "tidak perlu Ctrl+Z. Had setiap panggilan ialah 1460; di luar julat akan dibalas ERROR",
  "modul hanya melepaskan context SSL selepas semua sambungan padanya ditutup",
  "angka 0 di hujung = mod penimbal, datanya anda ambil sendiri dengan AT+QSSLRECV",
  "angka 1 di hujung = tolak terus, data masuk keluar terus dalam +QSSLURC berserta kandungannya, tanpa bacaan berasingan",
  "angka 2 di hujung = mod lut sinar, port AT menjadi saluran data",
  "membaca +QSSLRECV: 0 bermakna penimbal sudah kosong; hanya mod penimbal memerlukan arahan ini",
  ", julat 0–65535",
  " = tutup serta-merta tanpa menunggu"],
 'th-TH': [
  "0 = ไม่ตรวจสอบใด ๆ เลย; 1 = ตรวจสอบเซิร์ฟเวอร์ (ใน UFS ของโมดูลต้องมีใบรับรอง CA ที่เชื่อถือได้อยู่ก่อนแล้ว); 2 = ตรวจสอบสองทางทั้งเซิร์ฟเวอร์และไคลเอนต์ (ถ้าปลายทางร้องขอ ยังต้องมีใบรับรองไคลเอนต์และกุญแจส่วนตัวด้วย) คู่มือ §4 ระบุชัดว่า ถ้าตั้ง seclevel เป็น 1 หรือ 2 ต้องอัปโหลดใบรับรองด้วย AT+QFUPL ก่อน ⚠ คำอธิบายเดิมที่เขียนว่า «เครื่องมือนี้ส่งใบรับรองไม่ได้จึงล้มเหลวแน่นอน» นั้นผิด — PEM เป็น ASCII ล้วน และเมื่อ 2026-08-07 การทดสอบ P5 อัปโหลด ISRG Root X1 ขนาด 1939 ไบต์สำเร็จและผ่านการตรวจสอบแล้ว ขณะนี้ยังไม่มีปุ่มอัปโหลดในหน้าจอ จึงต้องเดินกระบวนการสองขั้นของ AT+QFUPL ด้วยมือ ⚠ อีกจุดคือ sni ค่าเริ่มต้นจากโรงงานคือ 0: เซิร์ฟเวอร์ที่วางหลายโดเมนบน IP เดียว (badssl.com เป็นแบบนั้น) จะส่งใบรับรองที่ไม่ตรงกลับมาถ้าไม่ส่ง SNI และการตรวจสอบจะล้มเหลวด้วยรหัส 566 แน่นอน",
  "หลังจากโมดูลตอบ > แล้ว มันจะส่งออกก็ต่อเมื่อนับครบจำนวนไบต์ที่คุณประกาศไว้พอดี ถ้าคำนวณความยาวผิดหรือยกเลิกกลางคัน พอร์ต AT จะค้างอยู่ในโหมดข้อมูลและกลืนทุกอย่างที่คุณพิมพ์ต่อไป — ส่ง ESC (0x1B) ด้วยปุ่มส่งไบต์ดิบในหน้า Hardware ก็ออกได้ ไม่ต้องปิดการเชื่อมต่อหรือรีสตาร์ตโมดูล ข้อมูลออกสู่เครือข่ายจริงและกินปริมาณการใช้งาน",
  "สอบถามเฉพาะการเชื่อมต่อที่มี clientID {0} โดยรายงานที่อยู่และพอร์ตปลายทาง พอร์ตต้นทาง รหัสสถานะ รหัส context ของ PDP และ SSL รวมถึงพอร์ต AT ที่ใช้อยู่",
  "ส่งข้อมูลความยาวคงที่ {1} ไบต์บน clientID {0}: หลังจากโมดูลตอบ > แล้ว จะส่งออกก็ต่อเมื่อได้รับครบ {2} ไบต์พอดี ",
  "อ่านจากบัฟเฟอร์รับของ clientID {0} ได้มากที่สุด {1} ไบต์ (ช่วง 0–1500 ค่าเริ่มต้น 1500); ",
  "เชื่อมต่อไปยัง {2}:{3} ผ่าน PDP context {0} และ SSL context {1}; clientID ของการเชื่อมต่อนี้คือ {4}; ",
  "ปิด clientID {0} และตั้ง close_timeout เป็น {1}",
  "ปิดการเชื่อมต่อ SSL บน clientID {0}; ถ้าไม่ใส่พารามิเตอร์เวลาจะใช้ค่าเริ่มต้น 10 วินาที; ",
  " วินาที",
  " คำว่า OK ที่ตอบมาทันทีหมายถึงรับคำสั่งไว้เท่านั้น ผลสำเร็จหรือล้มเหลวจะมาใน URC +QSSLOPEN",
  "ไม่ต้องส่ง Ctrl+Z ขีดจำกัดต่อครั้งคือ 1460 ถ้าเกินช่วงจะตอบ ERROR",
  "โมดูลจะปล่อย SSL context ก็ต่อเมื่อการเชื่อมต่อทั้งหมดบน context นั้นถูกปิดหมดแล้ว",
  "เลข 0 ท้ายสุด = โหมดบัฟเฟอร์ ข้อมูลต้องไปดึงเองด้วย AT+QSSLRECV",
  "เลข 1 ท้ายสุด = โหมดผลักตรง ข้อมูลที่ได้รับจะออกมาใน +QSSLURC พร้อมเนื้อหาเลย ไม่ต้องอ่านแยก",
  "เลข 2 ท้ายสุด = โหมดโปร่งใส พอร์ต AT กลายเป็นช่องทางข้อมูล",
  "ถ้าอ่านได้ +QSSLRECV: 0 แปลว่าบัฟเฟอร์ว่างแล้ว มีเพียงโหมดบัฟเฟอร์เท่านั้นที่ต้องใช้คำสั่งนี้",
  " ช่วง 0–65535",
  " = ปิดทันทีโดยไม่รอ"],
 'hi-IN': [
  "0 = कोई भी सत्यापन नहीं; 1 = सर्वर सत्यापित करें (मॉड्यूल के UFS में विश्वसनीय CA प्रमाणपत्र पहले से होना चाहिए); 2 = सर्वर और क्लाइंट दोनों का पारस्परिक सत्यापन (दूसरा छोर माँगे तो क्लाइंट प्रमाणपत्र और निजी कुंजी भी चाहिए)। नियमावली §4 साफ़ कहती है: seclevel 1 या 2 रखने पर पहले AT+QFUPL से प्रमाणपत्र चढ़ाना ज़रूरी है। ⚠ यहाँ पहले लिखा था «यह उपकरण प्रमाणपत्र भेज नहीं सकता इसलिए हमेशा विफल रहेगा» — वह ग़लत था। PEM सादा ASCII है, और 2026-08-07 को P5 दौर में 1939 बाइट का ISRG Root X1 चढ़ाकर सत्यापन पास किया गया। इंटरफ़ेस में अभी अपलोड बटन नहीं है, इसलिए AT+QFUPL का दो-चरण प्रवाह हाथ से चलाना पड़ता है। ⚠ यह भी ध्यान रखें कि sni का फ़ैक्टरी मान 0 है: एक ही IP पर कई डोमेन रखने वाला सर्वर (badssl.com ऐसा ही है) SNI न भेजने पर बेमेल प्रमाणपत्र लौटाता है और सत्यापन 566 के साथ ज़रूर विफल होता है।",
  "मॉड्यूल के > लौटाने के बाद वह तभी भेजता है जब आपके बताए हुए ठीक उतने बाइट गिन ले। लंबाई ग़लत हो या आप बीच में छोड़ दें, तो AT पोर्ट डेटा मोड में ही अटका रहता है और आगे जो कुछ आप टाइप करें उसे निगल जाता है — निकलने के लिए Hardware पृष्ठ के रॉ-बाइट बटन से ESC (0x1B) भेज दीजिए; कनेक्शन बंद करने या मॉड्यूल दोबारा चालू करने की ज़रूरत नहीं। डेटा सचमुच नेटवर्क पर जाता है और खर्च होता है।",
  "केवल clientID {0} वाले कनेक्शन की पूछताछ करता है, और दूरस्थ पता व पोर्ट, स्थानीय पोर्ट, स्थिति कोड, PDP तथा SSL context ID, और उपयोग में आ रहा AT पोर्ट बताता है।",
  "clientID {0} पर ठीक {1} बाइट भेजता है: मॉड्यूल के > लौटाने के बाद वह तभी प्रसारित करता है जब ठीक {2} बाइट आ चुके हों, ",
  "clientID {0} के प्राप्ति बफ़र से अधिकतम {1} बाइट पढ़ता है (सीमा 0–1500, डिफ़ॉल्ट 1500); ",
  "PDP context {0} और SSL context {1} से होकर {2}:{3} से जुड़ता है; इस कनेक्शन का clientID {4} है; ",
  "clientID {0} को बंद करता है और close_timeout को {1} पर सेट करता है",
  "clientID {0} का SSL कनेक्शन बंद करता है; समय-सीमा पैरामीटर न देने पर डिफ़ॉल्ट 10 सेकंड लागू होता है; ",
  " सेकंड",
  "। तुरंत आया OK केवल इतना बताता है कि आदेश स्वीकार हुआ — सफलता या विफलता +QSSLOPEN URC में आती है",
  "Ctrl+Z की ज़रूरत नहीं। प्रति कॉल सीमा 1460 है; सीमा से बाहर होने पर ERROR मिलता है",
  "मॉड्यूल SSL context तभी छोड़ता है जब उस पर के सारे कनेक्शन बंद हो जाएँ",
  "अंत का 0 = बफ़र मोड, डेटा आपको स्वयं AT+QSSLRECV से लेना होगा",
  "अंत का 1 = सीधा धक्का, आया हुआ डेटा सामग्री समेत सीधे +QSSLURC में निकलता है, अलग से पढ़ना नहीं पड़ता",
  "अंत का 2 = पारदर्शी मोड, AT पोर्ट ही डेटा चैनल बन जाता है",
  "+QSSLRECV: 0 पढ़ने का अर्थ है बफ़र ख़ाली है; यह आदेश केवल बफ़र मोड में चाहिए",
  ", सीमा 0–65535",
  " = बिना प्रतीक्षा किए तुरंत बंद"],
 'tr-TR': [
  "0 = hiçbir doğrulama yok; 1 = sunucuyu doğrula (modülün UFS'inde güvenilir bir CA sertifikası hâlihazırda bulunmalı); 2 = sunucu ve istemcinin karşılıklı doğrulaması (karşı taraf isterse ayrıca istemci sertifikası ve özel anahtar gerekir). Kılavuz §4 açıkça söylüyor: seclevel 1 veya 2 iken önce AT+QFUPL ile sertifika yüklenmelidir. ⚠ Buradaki eski not — «bu araç sertifika gönderemez, bu yüzden hep başarısız olur» — yanlıştı: PEM saf ASCII'dir ve 2026-08-07'de P5 turunda 1939 baytlık ISRG Root X1 yüklenip doğrulamadan geçildi. Arayüzde henüz yükleme düğmesi yok, dolayısıyla AT+QFUPL'un iki aşamalı akışını elle yürütmek gerekiyor. ⚠ Ayrıca sni fabrika değeri 0'dır: tek IP üzerinde birden çok alan adı barındıran bir sunucu (badssl.com böyledir) SNI gönderilmediğinde uyuşmayan bir sertifika döndürür ve doğrulama 566 ile kesinlikle başarısız olur.",
  "Modül > yanıtını verdikten sonra, ancak bildirdiğiniz bayt sayısını tam olarak saydığında gönderir. Uzunluk yanlışsa ya da yarıda bırakırsanız AT bağlantı noktası veri kipinde kalır ve sonrasında yazdığınız her şeyi yutar — çıkmak için Hardware sayfasındaki ham bayt düğmesiyle ESC (0x1B) gönderin; bağlantıyı kapatmanız ya da modülü yeniden başlatmanız gerekmez. Veri gerçekten ağa çıkar ve trafik harcar.",
  "Yalnızca clientID {0} olan bağlantıyı sorgular; uzak adres ve bağlantı noktasını, yerel bağlantı noktasını, durum kodunu, PDP ve SSL context kimliklerini ve kullanılan AT bağlantı noktasını bildirir.",
  "clientID {0} üzerinden tam {1} bayt gönderir: modül > yanıtını verdikten sonra, ancak tam {2} bayt geldiğinde iletir, ",
  "clientID {0} alım arabelleğinden en çok {1} bayt okur (aralık 0–1500, varsayılan 1500); ",
  "PDP context {0} ve SSL context {1} üzerinden {2}:{3} adresine bağlanır; bu bağlantının clientID'si {4}; ",
  "clientID {0} bağlantısını kapatır ve close_timeout değerini {1} yapar",
  "clientID {0} üzerindeki SSL bağlantısını kapatır; zaman aşımı parametresi verilmezse varsayılan 10 saniye geçerlidir; ",
  " saniye",
  ". Hemen dönen OK yalnızca komutun kabul edildiği anlamına gelir — başarı ya da başarısızlık +QSSLOPEN URC'siyle gelir",
  "Ctrl+Z gerekmez. Çağrı başına sınır 1460'tır; aralık dışında ERROR döner",
  "modül, SSL context'i ancak üzerindeki tüm bağlantılar kapandıktan sonra serbest bırakır",
  "sondaki 0 = arabellek kipi, veriyi AT+QSSLRECV ile kendiniz alırsınız",
  "sondaki 1 = doğrudan itme, gelen veri içeriğiyle birlikte doğrudan bir +QSSLURC içinde çıkar, ayrıca okumaya gerek yoktur",
  "sondaki 2 = saydam kip, AT bağlantı noktası veri kanalına dönüşür",
  "+QSSLRECV: 0 okunması arabelleğin boş olduğu anlamına gelir; bu komuta yalnızca arabellek kipinde ihtiyaç vardır",
  ", aralık 0–65535",
  " = beklemeden hemen kapat"],
 'ar-SA': [
  "0 = بلا أي تحقق؛ 1 = التحقق من الخادم (يجب أن تكون شهادة CA موثوقة موجودة سلفاً في وحدة UFS بالموديل)؛ 2 = تحقق متبادل من الخادم والعميل (وإذا طلب الطرف الآخر ذلك لزمت أيضاً شهادة عميل ومفتاح خاص). ينص الدليل §4 صراحةً: عند ضبط seclevel على 1 أو 2 يجب أولاً رفع شهادة بالأمر AT+QFUPL. ⚠ أما الملاحظة القديمة «هذه الأداة لا تستطيع إرسال الشهادات فالفشل حتمي» فكانت خاطئة —— صيغة PEM نص ASCII صِرف، وفي 2026-08-07 رُفعت في جولة P5 شهادة ISRG Root X1 بحجم 1939 بايت واجتازت التحقق. لا يوجد بعد زر رفع في الواجهة، لذا يُنفَّذ تدفق AT+QFUPL ذو المرحلتين يدوياً. ⚠ ولاحظ كذلك أن القيمة المصنعية لـ sni هي 0: فالخادم الذي يستضيف عدة نطاقات على عنوان IP واحد (وbadssl.com كذلك) يعيد شهادة غير مطابقة إن لم يُرسَل SNI، فيفشل التحقق حتماً بالرمز 566.",
  "بعد أن يردّ الموديل بالعلامة >، لا يُرسل إلا حين يُتِمّ عدّ العدد المُعلَن من البايتات بالضبط. وإذا أخطأت في الطول أو تراجعت في المنتصف، بقي منفذ AT في وضع البيانات وابتلع كل ما تكتبه بعد ذلك —— أرسل ESC (0x1B) بزر البايت الخام في صفحة Hardware لتخرج، ولا حاجة لإغلاق الاتصال ولا لإعادة تشغيل الموديل. البيانات تخرج فعلاً إلى الشبكة وتستهلك رصيداً.",
  "يستعلم فقط عن الاتصال ذي المعرّف clientID {0}، ويُبلغ عن العنوان والمنفذ البعيدين، والمنفذ المحلي، ورمز الحالة، ومعرّفي سياقي PDP وSSL، ومنفذ AT المستخدم.",
  "يرسل عبر clientID {0} ما مقداره {1} بايت بالضبط: بعد أن يردّ الموديل بالعلامة >، لا يبثّ إلا حين يصل بالضبط {2} بايت، ",
  "يقرأ من مخزن الاستقبال المؤقت للمعرّف clientID {0} ما لا يزيد على {1} بايت (المدى 0–1500، والافتراضي 1500)؛ ",
  "يتصل بـ {2}:{3} عبر سياق PDP رقم {0} وسياق SSL رقم {1}؛ ومعرّف هذا الاتصال clientID هو {4}؛ ",
  "يغلق المعرّف clientID {0} ويضبط close_timeout على {1}",
  "يغلق اتصال SSL على المعرّف clientID {0}؛ وبغير معامل المهلة تُطبَّق القيمة الافتراضية 10 ثوانٍ؛ ",
  " ثانية",
  ". وكلمة OK التي تظهر فوراً لا تعني إلا أن الأمر قُبل —— أما النجاح أو الإخفاق فيأتي في إشعار +QSSLOPEN",
  "ولا حاجة إلى Ctrl+Z. الحد لكل استدعاء 1460، وخارج المدى يُردّ بـ ERROR",
  "ولا يحرّر الموديل سياق SSL إلا بعد إغلاق جميع الاتصالات القائمة عليه",
  "الرقم 0 في آخر الأمر = وضع التخزين المؤقت، وعليك جلب البيانات بنفسك بالأمر AT+QSSLRECV",
  "الرقم 1 في آخر الأمر = الدفع المباشر، فالبيانات الواردة تخرج كما هي داخل إشعار +QSSLURC مع محتواها، بلا قراءة منفصلة",
  "الرقم 2 في آخر الأمر = الوضع الشفاف، فيصير منفذ AT قناةً للبيانات",
  "وظهور +QSSLRECV: 0 يعني أن المخزن المؤقت فارغ؛ ولا يحتاج هذا الأمر إلا وضع التخزين المؤقت",
  "، المدى 0–65535",
  " = الإغلاق فوراً بلا انتظار"],
 'he-IL': [
  "0 = בלי שום אימות; 1 = אימות השרת (אישור CA מהימן חייב כבר להימצא ב-UFS של המודול); 2 = אימות הדדי של שרת ולקוח (אם הצד השני דורש זאת נחוצים גם אישור לקוח ומפתח פרטי). המדריך §4 אומר במפורש: ב-seclevel 1 או 2 יש להעלות תחילה אישור באמצעות AT+QFUPL. ⚠ ההערה הישנה כאן — «הכלי הזה אינו יכול לשלוח אישורים ולכן זה תמיד ייכשל» — הייתה שגויה: PEM הוא ASCII טהור, וב-2026-08-07 סבב P5 העלה ISRG Root X1 בגודל 1939 בתים ועבר את האימות. עדיין אין כפתור העלאה בממשק, ולכן יש להריץ ידנית את התהליך הדו-שלבי של AT+QFUPL. ⚠ שימו לב גם ש-sni מגיע מהיצרן בערך 0: שרת שמארח כמה מתחמים על אותה כתובת IP (וכזה הוא badssl.com) יחזיר אישור שאינו תואם אם לא נשלח SNI, והאימות ייכשל בוודאות עם 566.",
  "אחרי שהמודול משיב >, הוא שולח רק לאחר שספר בדיוק את מספר הבתים שהצהרת עליו. אם האורך שגוי או שנטשת באמצע, יציאת ה-AT נשארת במצב נתונים ובולעת כל מה שתקליד לאחר מכן — שלח ESC (0x1B) בעזרת כפתור הבית הגולמי שבעמוד Hardware כדי לצאת; אין צורך לסגור את החיבור או להפעיל מחדש את המודול. הנתונים באמת יוצאים לרשת וצורכים תעבורה.",
  "מתשאל רק את החיבור בעל clientID {0}, ומדווח על הכתובת והפורט המרוחקים, הפורט המקומי, קוד המצב, מזהי הקשר של PDP ושל SSL, ויציאת ה-AT שבשימוש.",
  "שולח ב-clientID {0} בדיוק {1} בתים: לאחר שהמודול משיב >, הוא משדר רק כשהגיעו בדיוק {2} בתים, ",
  "קורא לכל היותר {1} בתים ממאגר הקליטה של clientID {0} (טווח 0–1500, ברירת מחדל 1500); ",
  "מתחבר אל {2}:{3} דרך הקשר PDP ‏{0} והקשר SSL ‏{1}; ה-clientID של חיבור זה הוא {4}; ",
  "סוגר את clientID {0} ומגדיר את close_timeout ל-{1}",
  "סוגר את חיבור ה-SSL ב-clientID {0}; ללא פרמטר פסק זמן חלה ברירת המחדל של 10 שניות; ",
  " שניות",
  ". ה-OK שמופיע מיד פירושו רק שהפקודה התקבלה — ההצלחה או הכישלון מגיעים ב-URC ‏+QSSLOPEN",
  "אין צורך ב-Ctrl+Z. המגבלה לכל קריאה היא 1460; מחוץ לטווח מתקבל ERROR",
  "המודול משחרר את הקשר ה-SSL רק לאחר שכל החיבורים שעליו נסגרו",
  "0 בסוף = מצב מאגר, את הנתונים אתה אוסף בעצמך עם AT+QSSLRECV",
  "1 בסוף = דחיפה ישירה, הנתונים הנכנסים יוצאים כמות שהם ב-+QSSLURC יחד עם תוכנם, בלי קריאה נפרדת",
  "2 בסוף = מצב שקוף, יציאת ה-AT הופכת לערוץ הנתונים",
  "קבלת +QSSLRECV: 0 פירושה שהמאגר ריק; רק מצב המאגר זקוק לפקודה הזו",
  ", טווח 0–65535",
  " = סגירה מיידית בלי להמתין"],
 'fa-IR': [
  "0 = بدون هیچ وارسی؛ 1 = وارسی کارساز (گواهی CA مورد اعتماد باید از پیش در UFS ماژول باشد)؛ 2 = وارسی دوسویهٔ کارساز و کارخواه (اگر طرف مقابل بخواهد، گواهی کارخواه و کلید خصوصی هم لازم است). راهنما §4 صریح می‌گوید: با seclevel برابر ۱ یا ۲ نخست باید گواهی را با AT+QFUPL بارگذاری کرد. ⚠ یادداشت قدیمی «این ابزار نمی‌تواند گواهی بفرستد پس حتماً شکست می‌خورد» نادرست بود —— PEM متن ASCII خالص است و در ۲۰۲۶-۰۸-۰۷ در دور P5 یک ISRG Root X1 به حجم ۱۹۳۹ بایت بارگذاری شد و وارسی را گذراند. هنوز دکمهٔ بارگذاری در رابط کاربری نیست، پس باید روند دومرحله‌ای AT+QFUPL را دستی پیش برد. ⚠ نیز توجه کنید که مقدار کارخانه‌ای sni برابر ۰ است: کارسازی که چند دامنه را روی یک IP دارد (badssl.com همین‌طور است) اگر SNI فرستاده نشود گواهی ناهمخوان برمی‌گرداند و وارسی حتماً با کد ۵۶۶ شکست می‌خورد.",
  "پس از آنکه ماژول > را برگرداند، تنها زمانی می‌فرستد که دقیقاً همان تعداد بایتی را که اعلام کرده‌اید شمرده باشد. اگر طول را اشتباه بزنید یا میان راه رها کنید، درگاه AT در حالت داده می‌ماند و هرچه بعد بنویسید می‌بلعد —— برای بیرون آمدن، ESC ‏(0x1B) را با دکمهٔ بایت خام در صفحهٔ Hardware بفرستید؛ نیازی به بستن اتصال یا راه‌اندازی دوبارهٔ ماژول نیست. داده واقعاً به شبکه می‌رود و مصرف دارد.",
  "تنها اتصال دارای clientID {0} را پرس‌وجو می‌کند و نشانی و درگاه دوردست، درگاه محلی، کد وضعیت، شناسهٔ بافت‌های PDP و SSL و درگاه AT در حال استفاده را گزارش می‌دهد.",
  "روی clientID {0} دقیقاً {1} بایت می‌فرستد: پس از آنکه ماژول > را برگرداند، تنها وقتی می‌فرستد که دقیقاً {2} بایت رسیده باشد، ",
  "از میان‌گیر دریافت clientID {0} حداکثر {1} بایت می‌خواند (بازهٔ 0–1500، پیش‌فرض 1500)؛ ",
  "از راه بافت PDP شمارهٔ {0} و بافت SSL شمارهٔ {1} به {2}:{3} وصل می‌شود؛ شناسهٔ این اتصال clientID برابر {4} است؛ ",
  "اتصال clientID {0} را می‌بندد و close_timeout را برابر {1} می‌گذارد",
  "اتصال SSL روی clientID {0} را می‌بندد؛ بدون پارامتر مهلت، پیش‌فرض ۱۰ ثانیه اعمال می‌شود؛ ",
  " ثانیه",
  ". واژهٔ OK که بی‌درنگ برمی‌گردد تنها یعنی فرمان پذیرفته شد —— کامیابی یا ناکامی در URC ‏+QSSLOPEN می‌آید",
  "به Ctrl+Z نیازی نیست. سقف هر فراخوانی ۱۴۶۰ است و بیرون از بازه ERROR برمی‌گردد",
  "ماژول بافت SSL را تنها پس از بسته شدن همهٔ اتصال‌های روی آن آزاد می‌کند",
  "عدد ۰ در پایان = حالت میان‌گیر؛ داده را خودتان با AT+QSSLRECV برمی‌دارید",
  "عدد ۱ در پایان = رانش مستقیم؛ دادهٔ رسیده همراه محتوایش مستقیم در +QSSLURC بیرون می‌آید و خواندن جداگانه لازم نیست",
  "عدد ۲ در پایان = حالت شفاف؛ درگاه AT خودش کانال داده می‌شود",
  "دیدن +QSSLRECV: 0 یعنی میان‌گیر خالی است؛ تنها حالت میان‌گیر به این فرمان نیاز دارد",
  "، بازهٔ 0–65535",
  " = بستن بی‌درنگ بدون انتظار"],
}


def main():
    os.makedirs(OUT, exist_ok=True)
    for lang, vals in T.items():
        assert len(vals) == len(KEYS), '%s: %d != %d' % (lang, len(vals), len(KEYS))
        json.dump(dict(zip(KEYS, vals)),
                  io.open(os.path.join(OUT, lang + '.json'), 'w', encoding='utf-8'),
                  ensure_ascii=False, indent=1)
        print('  %-7s %d 條' % (lang, len(vals)))
    print('完成 %d 種語言' % len(T))


if __name__ == '__main__':
    main()
