r"""第八批補譯：P7-B QuecLocator（QLBS）按鈕群與註解，43 條 × 17 語言。

⚠ QLBS 沒有官方文件收錄在本專案 ref/，原文裡「推測」兩字是刻意標示的 ——
翻譯時務必保留那個不確定性，不要翻成肯定語氣。
"""
import io
import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEYS = json.load(io.open(os.path.join(ROOT, 'i18n', 'tr14-source.json'), encoding='utf-8'))
OUT = os.path.join(ROOT, 'i18n', 'tr14')

T = {
 'en-US': [
  "Satellite-free network positioning: the module sends the Wi-Fi hotspots and cell towers it can see to Quectel's cloud and gets coordinates back, so it works indoors. ⚠ It needs a token from Quectel (this unit ships with none) — without one it always answers 702. ⚠ QuecLocator has no official document in this project's ref/, so everything below states only what was measured on 2026-08-07; anything inferred is marked as such",
  "List the seven configuration sub-items and their ranges (no traffic)",
  "Set the QuecLocator token (you have to request one from Quectel)",
  "⚠ Empty from the factory on this unit; without it AT+QLBS always answers 702 (measured 2026-08-07 — a made-up string gives 702 as well). Once set, reading it back shows only *, exactly like the FTP password",
  "the string issued by Quectel",
  "Read the current token (it comes back masked with *)",
  "Read the positioning server (this unit ships with www.queclocator.com:80)",
  "Change the positioning server address",
  "Server",
  "Format is \"host:port\". This unit's factory value is exactly that, so leave it alone unless Quectel tells you otherwise",
  "Read the query timeout (this unit ships with 60 seconds)",
  "Set the query timeout in seconds",
  "Timeout (s)",
  "Range 10-120 (as returned by AT+QLBSCFG=?), 60 on this unit from the factory",
  "Read the synchronous / asynchronous mode (0 on this unit from the factory)",
  "Switch between synchronous and asynchronous",
  "0 = synchronous (the command waits for the result); 1 = asynchronous (OK comes back first, the result follows separately). ⚠ These two meanings are inferred from the sub-item's name — without a token this unit cannot verify them",
  "Read the latitude/longitude output order. ⚠ You set it with the lowercase key latorder, but the module reads it back as camel-case latOrder",
  "Read whether the response carries a timestamp (read back as withTime, 0 on this unit from the factory)",
  "Read whether the positioning result is used to correct the module clock (read back as timeUpdate, 0 on this unit from the factory)",
  "Run a network fix. ⚠ Needs a token and an active PDP context, and it costs data. This is the only positioning method that works indoors — it does not use satellites",
  "List QuecLocator's seven configuration sub-items with their ranges (no traffic, nothing goes over the air). Measured on this unit 2026-08-07: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "Set the QuecLocator token. ⚠ You have to request this string from Quectel; this unit ships with none — without it AT+QLBS always answers 702 (measured 2026-08-07, a made-up token gives 702 too). Reading it back shows only *",
  "Read the current value of that QuecLocator sub-item (no traffic)",
  "Set a QuecLocator sub-item (no traffic; the setting is stored in the module)",
  "Run a network fix: the module sends the Wi-Fi hotspots and cell towers it can see to the QuecLocator cloud and gets coordinates back. ⚠ Needs a token and an active PDP context, and it costs data. This is the only positioning method that works indoors — no satellites involved, so it still works where GNSS sees nothing",
  "QuecLocator token = {0}",
  "Network positioning failed — error {0}",
  "Network positioning failed — error {0}: {1}",
  "Network positioning succeeded, fields returned: {0}",
  "Synchronous — the command waits for the result; inferred, and 0 is what this unit ships with",
  "Asynchronous — OK comes back first and the fix follows separately; inferred",
  "Default order — the factory value measured on this unit",
  "Latitude and longitude swapped — inferred",
  "Response carries no timestamp — the factory value measured on this unit",
  "Response carries a timestamp — inferred",
  "Do not use the positioning service's time to correct the module clock — the factory value measured on this unit",
  "Use the time returned by the positioning service to correct the module clock — inferred",
  ". Measured 2026-08-07: both a missing token and an invalid one give this code; the token has to be requested from Quectel and this unit ships with none",
  "Positioning request accepted",
  "(QuecLocator has no official document in this project's ref/, so the meaning of this code is unconfirmed)",
  "(the module masks it with * when reading back; with no token set AT+QLBS answers 702)",
  "(the order depends on AT+QLBSCFG=\"latorder\"; with no token this unit could not verify it, so the field mapping is unconfirmed)"],
 'ja-JP': [
  "衛星を使わないネットワーク測位：モジュールが見えている Wi-Fi アクセスポイントと基地局の情報を Quectel のクラウドへ送って座標を受け取るので、屋内でも使えます。⚠ Quectel が発行する token が必要で、本機は出荷時が空 —— それがないと必ず 702 が返ります。⚠ QuecLocator の公式ドキュメントは本プロジェクトの ref/ に収録されていないため、以下は 2026-08-07 の実測事実のみを記載し、推測部分にはその旨を明示しています",
  "7 つの設定項目とその範囲を一覧表示（通信量なし）",
  "QuecLocator の token を設定（Quectel への申請が必要）",
  "⚠ 本機は出荷時が空です。これがないと AT+QLBS は必ず 702 を返します（2026-08-07 実測。でたらめな文字列でも 702）。設定後に読み出すと FTP のパスワードと同じく * で伏せられます",
  "Quectel から発行される文字列",
  "現在の token を確認（* で伏せられて返ります）",
  "測位サーバーを確認（本機の出荷値は www.queclocator.com:80）",
  "測位サーバーのアドレスを変更",
  "サーバー",
  "形式は「ホスト:ポート」。本機の出荷値がまさにこれなので、Quectel から別途指定がない限り変更不要です",
  "問い合わせのタイムアウトを確認（本機の出荷値は 60 秒）",
  "問い合わせのタイムアウト秒数を設定",
  "タイムアウト（秒）",
  "範囲 10-120（AT+QLBSCFG=? の実際の応答）、本機の出荷値は 60",
  "同期／非同期モードを確認（本機の出荷値は 0）",
  "同期と非同期を切り替え",
  "0＝同期（コマンドが結果を待つ）、1＝非同期（先に OK が返り、結果は後から別に届く）。⚠ この 2 つの意味は項目名から推測したもので、token がない本機では検証できていません",
  "緯度経度の出力順を確認。⚠ 設定時のキーは小文字の latorder ですが、モジュールが読み返すときはキャメルケースの latOrder です",
  "応答に時刻が付くかどうかを確認（読み出し時のキーは withTime、本機の出荷値は 0）",
  "測位結果でモジュールの時計を補正するかどうかを確認（読み出し時のキーは timeUpdate、本機の出荷値は 0）",
  "ネットワーク測位を実行。⚠ token と有効な PDP context が必要で、通信量が発生します。屋内で使える唯一の測位手段です —— 衛星を使いません",
  "QuecLocator の 7 つの設定項目と各範囲を一覧表示（通信量なし、電波に出ません）。本機 2026-08-07 実測：asynch(0,1)／timeout(10-120)／server／token／timeupdate(0,1)／withtime(0,1)／latorder(0,1)",
  "QuecLocator の token を設定。⚠ この文字列は Quectel への申請が必要で、本機は出荷時が空 —— それがないと AT+QLBS は必ず 702 を返します（2026-08-07 実測。でたらめな token でも 702）。読み出し時は * で伏せられます",
  "その QuecLocator 設定項目の現在値を確認（通信量なし）",
  "QuecLocator の設定項目を変更（通信量なし。設定はモジュールに保存されます）",
  "ネットワーク測位を実行：モジュールが見えている Wi-Fi アクセスポイントと基地局の情報を QuecLocator のクラウドへ送って座標を受け取ります。⚠ token と有効な PDP context が必要で、通信量が発生します。屋内で使える唯一の測位手段です —— 衛星を使わないので、GNSS が何も見えない場所でも測位できます",
  "QuecLocator の token＝{0}",
  "ネットワーク測位に失敗 —— エラー {0}",
  "ネットワーク測位に失敗 —— エラー {0}：{1}",
  "ネットワーク測位に成功。返ってきたフィールド：{0}",
  "同期 —— コマンドが結果を待ちます。推測ですが、本機の出荷値がこの 0 です",
  "非同期 —— 先に OK が返り、測位結果は後から別に届きます。推測",
  "既定の順序 —— 本機で実測した出荷値",
  "緯度と経度を入れ替え —— 推測",
  "応答に時刻を付けない —— 本機で実測した出荷値",
  "応答に時刻を付ける —— 推測",
  "測位サービスの時刻でモジュールの時計を補正しない —— 本機で実測した出荷値",
  "測位サービスが返す時刻でモジュールの時計を補正する —— 推測",
  "。2026-08-07 実測：token 未設定でも無効な token でも同じこのコードが返ります。token は Quectel への申請が必要で、本機は出荷時が空です",
  "測位要求を受け付けました",
  "（QuecLocator の公式ドキュメントは本プロジェクトの ref/ に収録されていないため、このコードの意味は未確認です）",
  "（読み出し時はモジュールが * で伏せます。token 未設定だと AT+QLBS は 702 を返します）",
  "（順序は AT+QLBSCFG=\"latorder\" の影響を受けます。token がない本機では実測できておらず、フィールドの対応は未確認です）"],
 'de-DE': [
  "Ortung ohne Satelliten: Das Modul schickt die sichtbaren WLAN-Hotspots und Funkzellen an die Quectel-Cloud und bekommt Koordinaten zurück — funktioniert also auch drinnen. ⚠ Dafür braucht es ein Token von Quectel, dieses Gerät wird ohne ausgeliefert — ohne Token kommt immer 702. ⚠ Zu QuecLocator liegt in ref/ dieses Projekts kein offizielles Dokument, deshalb steht unten nur, was am 2026-08-07 gemessen wurde; Vermutetes ist als solches gekennzeichnet",
  "Die sieben Konfigurationspunkte samt Wertebereich auflisten (kein Datenverbrauch)",
  "Das QuecLocator-Token setzen (muss bei Quectel beantragt werden)",
  "⚠ Auf diesem Gerät ab Werk leer; ohne Token antwortet AT+QLBS immer mit 702 (gemessen 2026-08-07 — auch ein erfundener String liefert 702). Einmal gesetzt, zeigt das Auslesen nur noch *, genau wie beim FTP-Passwort",
  "die von Quectel ausgegebene Zeichenkette",
  "Das aktuelle Token auslesen (kommt mit * maskiert zurück)",
  "Den Ortungsserver auslesen (dieses Gerät wird mit www.queclocator.com:80 ausgeliefert)",
  "Die Adresse des Ortungsservers ändern",
  "Server",
  "Format „Host:Port“. Der Werkswert dieses Geräts ist genau das — lassen Sie ihn stehen, sofern Quectel nichts anderes vorgibt",
  "Das Abfrage-Zeitlimit auslesen (dieses Gerät wird mit 60 Sekunden ausgeliefert)",
  "Das Abfrage-Zeitlimit in Sekunden setzen",
  "Zeitlimit (s)",
  "Bereich 10-120 (so von AT+QLBSCFG=? zurückgeliefert), ab Werk 60 auf diesem Gerät",
  "Den synchronen / asynchronen Modus auslesen (ab Werk 0 auf diesem Gerät)",
  "Zwischen synchron und asynchron umschalten",
  "0 = synchron (der Befehl wartet auf das Ergebnis); 1 = asynchron (erst kommt OK, das Ergebnis folgt getrennt). ⚠ Diese beiden Bedeutungen sind aus dem Namen des Punktes erschlossen — ohne Token lässt sich das auf diesem Gerät nicht nachprüfen",
  "Die Reihenfolge von Breiten- und Längengrad auslesen. ⚠ Gesetzt wird mit dem kleingeschriebenen Schlüssel latorder, ausgelesen meldet das Modul aber das Binnenmajuskel-latOrder",
  "Auslesen, ob die Antwort einen Zeitstempel trägt (ausgelesen als withTime, ab Werk 0 auf diesem Gerät)",
  "Auslesen, ob das Ortungsergebnis die Moduluhr korrigiert (ausgelesen als timeUpdate, ab Werk 0 auf diesem Gerät)",
  "Eine Netzortung ausführen. ⚠ Braucht ein Token und einen aktiven PDP-Context und kostet Datenvolumen. Es ist die einzige Ortung, die drinnen funktioniert — sie kommt ohne Satelliten aus",
  "Die sieben Konfigurationspunkte von QuecLocator samt Bereich auflisten (kein Datenverbrauch, nichts geht über die Luftschnittstelle). Auf diesem Gerät am 2026-08-07 gemessen: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "Das QuecLocator-Token setzen. ⚠ Diese Zeichenkette muss bei Quectel beantragt werden, dieses Gerät wird ohne ausgeliefert — ohne sie antwortet AT+QLBS immer mit 702 (gemessen 2026-08-07, auch ein erfundenes Token liefert 702). Beim Auslesen erscheinen nur *",
  "Den aktuellen Wert dieses QuecLocator-Punktes auslesen (kein Datenverbrauch)",
  "Einen QuecLocator-Punkt setzen (kein Datenverbrauch; die Einstellung wird im Modul abgelegt)",
  "Eine Netzortung ausführen: Das Modul schickt die sichtbaren WLAN-Hotspots und Funkzellen an die QuecLocator-Cloud und bekommt Koordinaten zurück. ⚠ Braucht ein Token und einen aktiven PDP-Context und kostet Datenvolumen. Es ist die einzige Ortung, die drinnen funktioniert — ohne Satelliten, also auch dort, wo GNSS nichts sieht",
  "QuecLocator-Token = {0}",
  "Netzortung fehlgeschlagen — Fehler {0}",
  "Netzortung fehlgeschlagen — Fehler {0}: {1}",
  "Netzortung erfolgreich, zurückgegebene Felder: {0}",
  "Synchron — der Befehl wartet auf das Ergebnis; erschlossen, und 0 ist der Werkswert dieses Geräts",
  "Asynchron — erst kommt OK, die Ortung folgt getrennt; erschlossen",
  "Standardreihenfolge — der auf diesem Gerät gemessene Werkswert",
  "Breiten- und Längengrad vertauscht — erschlossen",
  "Antwort ohne Zeitstempel — der auf diesem Gerät gemessene Werkswert",
  "Antwort mit Zeitstempel — erschlossen",
  "Die Zeit des Ortungsdienstes nicht zur Korrektur der Moduluhr verwenden — der auf diesem Gerät gemessene Werkswert",
  "Die vom Ortungsdienst gelieferte Zeit zur Korrektur der Moduluhr verwenden — erschlossen",
  ". Gemessen 2026-08-07: Sowohl ein fehlendes als auch ein ungültiges Token liefern diesen Code; das Token muss bei Quectel beantragt werden und dieses Gerät wird ohne ausgeliefert",
  "Ortungsanfrage angenommen",
  "(Zu QuecLocator liegt in ref/ dieses Projekts kein offizielles Dokument, die Bedeutung dieses Codes ist daher unbestätigt)",
  "(das Modul maskiert es beim Auslesen mit *; ohne gesetztes Token antwortet AT+QLBS mit 702)",
  "(die Reihenfolge hängt von AT+QLBSCFG=\"latorder\" ab; ohne Token ließ sich das auf diesem Gerät nicht prüfen, die Feldzuordnung ist also unbestätigt)"],
 'fr-FR': [
  "Positionnement réseau sans satellites : le module envoie au nuage de Quectel les points d'accès Wi-Fi et les cellules qu'il voit, et reçoit des coordonnées en retour — cela fonctionne donc à l'intérieur. ⚠ Il faut un token délivré par Quectel ; cet appareil est livré sans, et sans token la réponse est toujours 702. ⚠ QuecLocator n'a aucun document officiel dans le ref/ de ce projet : tout ce qui suit ne rapporte que ce qui a été mesuré le 2026-08-07, et ce qui relève de la déduction est signalé comme tel",
  "Lister les sept sous-éléments de configuration et leurs plages (sans trafic)",
  "Définir le token QuecLocator (à demander à Quectel)",
  "⚠ Vide d'usine sur cet appareil ; sans lui AT+QLBS répond toujours 702 (mesuré le 2026-08-07 — une chaîne inventée donne 702 elle aussi). Une fois défini, la relecture n'affiche que des *, exactement comme le mot de passe FTP",
  "la chaîne délivrée par Quectel",
  "Lire le token actuel (il revient masqué par des *)",
  "Lire le serveur de positionnement (cet appareil est livré avec www.queclocator.com:80)",
  "Changer l'adresse du serveur de positionnement",
  "Serveur",
  "Format « hôte:port ». La valeur d'usine de cet appareil est exactement celle-là : n'y touchez pas sauf indication contraire de Quectel",
  "Lire le délai d'attente de la requête (cet appareil est livré avec 60 secondes)",
  "Définir le délai d'attente de la requête en secondes",
  "Délai (s)",
  "Plage 10-120 (telle que renvoyée par AT+QLBSCFG=?), 60 d'usine sur cet appareil",
  "Lire le mode synchrone / asynchrone (0 d'usine sur cet appareil)",
  "Basculer entre synchrone et asynchrone",
  "0 = synchrone (la commande attend le résultat) ; 1 = asynchrone (le OK revient d'abord, le résultat suit séparément). ⚠ Ces deux significations sont déduites du nom du sous-élément — sans token, cet appareil ne permet pas de les vérifier",
  "Lire l'ordre de sortie latitude/longitude. ⚠ On le définit avec la clé en minuscules latorder, mais le module le relit sous la forme camel latOrder",
  "Lire si la réponse porte un horodatage (relu sous le nom withTime, 0 d'usine sur cet appareil)",
  "Lire si le résultat de positionnement corrige l'horloge du module (relu sous le nom timeUpdate, 0 d'usine sur cet appareil)",
  "Lancer un positionnement réseau. ⚠ Nécessite un token et un contexte PDP actif, et consomme des données. C'est le seul positionnement qui fonctionne à l'intérieur — il n'utilise pas les satellites",
  "Lister les sept sous-éléments de configuration de QuecLocator avec leurs plages (sans trafic, rien ne part sur les ondes). Mesuré sur cet appareil le 2026-08-07 : asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "Définir le token QuecLocator. ⚠ Cette chaîne doit être demandée à Quectel ; cet appareil est livré sans — sans elle AT+QLBS répond toujours 702 (mesuré le 2026-08-07, un token inventé donne 702 aussi). À la relecture, seuls des * apparaissent",
  "Lire la valeur actuelle de ce sous-élément QuecLocator (sans trafic)",
  "Définir un sous-élément QuecLocator (sans trafic ; le réglage est stocké dans le module)",
  "Lancer un positionnement réseau : le module envoie au nuage QuecLocator les points d'accès Wi-Fi et les cellules qu'il voit, et reçoit des coordonnées. ⚠ Nécessite un token et un contexte PDP actif, et consomme des données. C'est le seul positionnement qui fonctionne à l'intérieur — sans satellites, donc là même où le GNSS ne voit rien",
  "Token QuecLocator = {0}",
  "Échec du positionnement réseau — erreur {0}",
  "Échec du positionnement réseau — erreur {0} : {1}",
  "Positionnement réseau réussi, champs renvoyés : {0}",
  "Synchrone — la commande attend le résultat ; déduit, et 0 est la valeur d'usine de cet appareil",
  "Asynchrone — le OK revient d'abord, le point suit séparément ; déduit",
  "Ordre par défaut — la valeur d'usine mesurée sur cet appareil",
  "Latitude et longitude inversées — déduit",
  "Réponse sans horodatage — la valeur d'usine mesurée sur cet appareil",
  "Réponse avec horodatage — déduit",
  "Ne pas utiliser l'heure du service de positionnement pour corriger l'horloge du module — la valeur d'usine mesurée sur cet appareil",
  "Utiliser l'heure renvoyée par le service de positionnement pour corriger l'horloge du module — déduit",
  ". Mesuré le 2026-08-07 : un token absent comme un token invalide donnent ce même code ; le token doit être demandé à Quectel et cet appareil est livré sans",
  "Demande de positionnement acceptée",
  "(QuecLocator n'a aucun document officiel dans le ref/ de ce projet, la signification de ce code reste donc à confirmer)",
  "(le module le masque par des * à la relecture ; sans token défini, AT+QLBS répond 702)",
  "(l'ordre dépend de AT+QLBSCFG=\"latorder\" ; sans token, cet appareil n'a pas permis de le vérifier, la correspondance des champs reste donc à confirmer)"],
 'es-ES': [
  "Posicionamiento por red sin satélites: el módulo envía a la nube de Quectel los puntos de acceso Wi-Fi y las celdas que ve, y recibe coordenadas, así que funciona en interiores. ⚠ Hace falta un token de Quectel; esta unidad viene sin él, y sin token siempre responde 702. ⚠ QuecLocator no tiene ningún documento oficial en el ref/ de este proyecto, así que lo que sigue solo recoge lo medido el 2026-08-07; lo deducido está marcado como tal",
  "Listar los siete subelementos de configuración y sus rangos (sin tráfico)",
  "Establecer el token de QuecLocator (hay que solicitarlo a Quectel)",
  "⚠ Vacío de fábrica en esta unidad; sin él AT+QLBS responde siempre 702 (medido el 2026-08-07: una cadena inventada también da 702). Una vez puesto, al leerlo solo se ven *, igual que la contraseña de FTP",
  "la cadena que expide Quectel",
  "Leer el token actual (vuelve enmascarado con *)",
  "Leer el servidor de posicionamiento (esta unidad viene con www.queclocator.com:80)",
  "Cambiar la dirección del servidor de posicionamiento",
  "Servidor",
  "Formato «host:puerto». El valor de fábrica de esta unidad es justo ese, así que no lo toques salvo que Quectel indique otra cosa",
  "Leer el tiempo de espera de la consulta (esta unidad viene con 60 segundos)",
  "Establecer el tiempo de espera de la consulta en segundos",
  "Tiempo de espera (s)",
  "Rango 10-120 (según devuelve AT+QLBSCFG=?), 60 de fábrica en esta unidad",
  "Leer el modo síncrono / asíncrono (0 de fábrica en esta unidad)",
  "Cambiar entre síncrono y asíncrono",
  "0 = síncrono (el comando espera el resultado); 1 = asíncrono (primero vuelve OK y el resultado llega aparte). ⚠ Estos dos significados están deducidos del nombre del subelemento: sin token esta unidad no permite comprobarlos",
  "Leer el orden de salida de latitud y longitud. ⚠ Se fija con la clave en minúsculas latorder, pero el módulo la devuelve en camel latOrder",
  "Leer si la respuesta lleva marca de tiempo (se devuelve como withTime, 0 de fábrica en esta unidad)",
  "Leer si el resultado de posicionamiento corrige el reloj del módulo (se devuelve como timeUpdate, 0 de fábrica en esta unidad)",
  "Ejecutar un posicionamiento por red. ⚠ Necesita token y un contexto PDP activo, y consume datos. Es el único posicionamiento que funciona en interiores: no usa satélites",
  "Listar los siete subelementos de configuración de QuecLocator con sus rangos (sin tráfico, no sale nada por el aire). Medido en esta unidad el 2026-08-07: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "Establecer el token de QuecLocator. ⚠ Esta cadena hay que solicitarla a Quectel; esta unidad viene sin ella, y sin ella AT+QLBS responde siempre 702 (medido el 2026-08-07, un token inventado también da 702). Al leerla solo aparecen *",
  "Leer el valor actual de ese subelemento de QuecLocator (sin tráfico)",
  "Establecer un subelemento de QuecLocator (sin tráfico; el ajuste queda guardado en el módulo)",
  "Ejecutar un posicionamiento por red: el módulo envía a la nube de QuecLocator los puntos de acceso Wi-Fi y las celdas que ve, y recibe coordenadas. ⚠ Necesita token y un contexto PDP activo, y consume datos. Es el único posicionamiento que funciona en interiores: sin satélites, así que sirve incluso donde el GNSS no ve nada",
  "Token de QuecLocator = {0}",
  "Falló el posicionamiento por red — error {0}",
  "Falló el posicionamiento por red — error {0}: {1}",
  "Posicionamiento por red correcto, campos devueltos: {0}",
  "Síncrono: el comando espera el resultado; deducido, y 0 es el valor de fábrica de esta unidad",
  "Asíncrono: primero vuelve OK y la posición llega aparte; deducido",
  "Orden predeterminado: el valor de fábrica medido en esta unidad",
  "Latitud y longitud intercambiadas: deducido",
  "La respuesta no lleva marca de tiempo: el valor de fábrica medido en esta unidad",
  "La respuesta lleva marca de tiempo: deducido",
  "No usar la hora del servicio de posicionamiento para corregir el reloj del módulo: el valor de fábrica medido en esta unidad",
  "Usar la hora que devuelve el servicio de posicionamiento para corregir el reloj del módulo: deducido",
  ". Medido el 2026-08-07: tanto la falta de token como un token inválido dan este mismo código; el token se solicita a Quectel y esta unidad viene sin él",
  "Solicitud de posicionamiento aceptada",
  "(QuecLocator no tiene ningún documento oficial en el ref/ de este proyecto, así que el significado de este código está sin confirmar)",
  "(el módulo lo enmascara con * al leerlo; sin token puesto, AT+QLBS responde 702)",
  "(el orden depende de AT+QLBSCFG=\"latorder\"; sin token esta unidad no permitió comprobarlo, así que la correspondencia de campos está sin confirmar)"],
 'pt-PT': [
  "Localização por rede sem satélites: o módulo envia para a nuvem da Quectel os pontos de acesso Wi-Fi e as células que vê e recebe coordenadas, pelo que funciona dentro de portas. ⚠ É preciso um token da Quectel; esta unidade vem sem ele e, sem token, a resposta é sempre 702. ⚠ O QuecLocator não tem qualquer documento oficial no ref/ deste projeto, por isso o que se segue regista apenas o que foi medido a 2026-08-07; o que é dedução está assinalado como tal",
  "Listar os sete subitens de configuração e os respetivos intervalos (sem tráfego)",
  "Definir o token do QuecLocator (tem de ser pedido à Quectel)",
  "⚠ Vazio de fábrica nesta unidade; sem ele o AT+QLBS responde sempre 702 (medido a 2026-08-07 — uma cadeia inventada dá 702 também). Depois de definido, ao ler só aparecem *, tal como acontece com a palavra-passe de FTP",
  "a cadeia emitida pela Quectel",
  "Ler o token atual (volta mascarado com *)",
  "Ler o servidor de localização (esta unidade vem com www.queclocator.com:80)",
  "Alterar o endereço do servidor de localização",
  "Servidor",
  "Formato «anfitrião:porta». O valor de fábrica desta unidade é exatamente esse, por isso não lhe toque a não ser que a Quectel indique outra coisa",
  "Ler o tempo limite da consulta (esta unidade vem com 60 segundos)",
  "Definir o tempo limite da consulta em segundos",
  "Tempo limite (s)",
  "Intervalo 10-120 (conforme devolvido por AT+QLBSCFG=?), 60 de fábrica nesta unidade",
  "Ler o modo síncrono / assíncrono (0 de fábrica nesta unidade)",
  "Alternar entre síncrono e assíncrono",
  "0 = síncrono (o comando espera pelo resultado); 1 = assíncrono (o OK volta primeiro e o resultado chega à parte). ⚠ Estes dois significados foram deduzidos do nome do subitem — sem token esta unidade não permite verificá-los",
  "Ler a ordem de saída de latitude e longitude. ⚠ Define-se com a chave em minúsculas latorder, mas o módulo devolve-a em camel latOrder",
  "Ler se a resposta traz marca temporal (devolvida como withTime, 0 de fábrica nesta unidade)",
  "Ler se o resultado da localização corrige o relógio do módulo (devolvido como timeUpdate, 0 de fábrica nesta unidade)",
  "Executar uma localização por rede. ⚠ Precisa de token e de um contexto PDP ativo, e consome dados. É a única localização que funciona dentro de portas — não usa satélites",
  "Listar os sete subitens de configuração do QuecLocator com os respetivos intervalos (sem tráfego, nada sai pelo ar). Medido nesta unidade a 2026-08-07: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "Definir o token do QuecLocator. ⚠ Esta cadeia tem de ser pedida à Quectel; esta unidade vem sem ela e, sem ela, o AT+QLBS responde sempre 702 (medido a 2026-08-07, um token inventado dá 702 também). Ao ler, só aparecem *",
  "Ler o valor atual desse subitem do QuecLocator (sem tráfego)",
  "Definir um subitem do QuecLocator (sem tráfego; a definição fica guardada no módulo)",
  "Executar uma localização por rede: o módulo envia para a nuvem do QuecLocator os pontos de acesso Wi-Fi e as células que vê e recebe coordenadas. ⚠ Precisa de token e de um contexto PDP ativo, e consome dados. É a única localização que funciona dentro de portas — sem satélites, por isso serve mesmo onde o GNSS não vê nada",
  "Token do QuecLocator = {0}",
  "Localização por rede falhou — erro {0}",
  "Localização por rede falhou — erro {0}: {1}",
  "Localização por rede bem-sucedida, campos devolvidos: {0}",
  "Síncrono — o comando espera pelo resultado; deduzido, e 0 é o valor de fábrica desta unidade",
  "Assíncrono — o OK volta primeiro e a posição chega à parte; deduzido",
  "Ordem predefinida — o valor de fábrica medido nesta unidade",
  "Latitude e longitude trocadas — deduzido",
  "Resposta sem marca temporal — o valor de fábrica medido nesta unidade",
  "Resposta com marca temporal — deduzido",
  "Não usar a hora do serviço de localização para corrigir o relógio do módulo — o valor de fábrica medido nesta unidade",
  "Usar a hora devolvida pelo serviço de localização para corrigir o relógio do módulo — deduzido",
  ". Medido a 2026-08-07: tanto a falta de token como um token inválido dão este mesmo código; o token pede-se à Quectel e esta unidade vem sem ele",
  "Pedido de localização aceite",
  "(o QuecLocator não tem qualquer documento oficial no ref/ deste projeto, pelo que o significado deste código está por confirmar)",
  "(o módulo mascara-o com * ao ler; sem token definido, o AT+QLBS responde 702)",
  "(a ordem depende de AT+QLBSCFG=\"latorder\"; sem token esta unidade não permitiu verificá-la, pelo que a correspondência dos campos está por confirmar)"],
 'it-IT': [
  "Localizzazione di rete senza satelliti: il modulo manda al cloud di Quectel gli hotspot Wi-Fi e le celle che vede e riceve le coordinate, quindi funziona anche al chiuso. ⚠ Serve un token rilasciato da Quectel; questa unità ne è priva di fabbrica e senza token la risposta è sempre 702. ⚠ QuecLocator non ha alcun documento ufficiale nel ref/ di questo progetto, perciò quanto segue riporta solo ciò che è stato misurato il 2026-08-07; ciò che è dedotto è segnalato come tale",
  "Elenca i sette sotto-elementi di configurazione e i relativi intervalli (nessun traffico)",
  "Imposta il token di QuecLocator (va richiesto a Quectel)",
  "⚠ Vuoto di fabbrica su questa unità; senza di esso AT+QLBS risponde sempre 702 (misurato il 2026-08-07: anche una stringa inventata dà 702). Una volta impostato, in lettura si vedono solo *, esattamente come per la password FTP",
  "la stringa rilasciata da Quectel",
  "Legge il token attuale (torna mascherato con *)",
  "Legge il server di localizzazione (questa unità arriva con www.queclocator.com:80)",
  "Cambia l'indirizzo del server di localizzazione",
  "Server",
  "Formato «host:porta». Il valore di fabbrica di questa unità è proprio quello: non toccarlo se non su indicazione di Quectel",
  "Legge il timeout della richiesta (questa unità arriva con 60 secondi)",
  "Imposta il timeout della richiesta in secondi",
  "Timeout (s)",
  "Intervallo 10-120 (come restituito da AT+QLBSCFG=?), 60 di fabbrica su questa unità",
  "Legge la modalità sincrona / asincrona (0 di fabbrica su questa unità)",
  "Passa da sincrono ad asincrono e viceversa",
  "0 = sincrono (il comando attende il risultato); 1 = asincrono (prima torna OK, il risultato arriva a parte). ⚠ Questi due significati sono dedotti dal nome del sotto-elemento: senza token questa unità non consente di verificarli",
  "Legge l'ordine di uscita di latitudine e longitudine. ⚠ Si imposta con la chiave minuscola latorder, ma il modulo la rilegge in camel latOrder",
  "Legge se la risposta porta un orario (rilegge come withTime, 0 di fabbrica su questa unità)",
  "Legge se il risultato della localizzazione corregge l'orologio del modulo (rilegge come timeUpdate, 0 di fabbrica su questa unità)",
  "Esegue una localizzazione di rete. ⚠ Richiede un token e un contesto PDP attivo e consuma traffico. È l'unica localizzazione che funziona al chiuso: non usa i satelliti",
  "Elenca i sette sotto-elementi di configurazione di QuecLocator con i relativi intervalli (nessun traffico, non esce nulla via radio). Misurato su questa unità il 2026-08-07: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "Imposta il token di QuecLocator. ⚠ Questa stringa va richiesta a Quectel; questa unità ne è priva e senza di essa AT+QLBS risponde sempre 702 (misurato il 2026-08-07, anche un token inventato dà 702). In lettura si vedono solo *",
  "Legge il valore attuale di quel sotto-elemento di QuecLocator (nessun traffico)",
  "Imposta un sotto-elemento di QuecLocator (nessun traffico; l'impostazione resta memorizzata nel modulo)",
  "Esegue una localizzazione di rete: il modulo manda al cloud di QuecLocator gli hotspot Wi-Fi e le celle che vede e riceve le coordinate. ⚠ Richiede un token e un contesto PDP attivo e consuma traffico. È l'unica localizzazione che funziona al chiuso: senza satelliti, quindi anche dove il GNSS non vede nulla",
  "Token di QuecLocator = {0}",
  "Localizzazione di rete fallita — errore {0}",
  "Localizzazione di rete fallita — errore {0}: {1}",
  "Localizzazione di rete riuscita, campi restituiti: {0}",
  "Sincrono — il comando attende il risultato; dedotto, e 0 è il valore di fabbrica di questa unità",
  "Asincrono — prima torna OK, la posizione arriva a parte; dedotto",
  "Ordine predefinito — il valore di fabbrica misurato su questa unità",
  "Latitudine e longitudine invertite — dedotto",
  "Risposta senza orario — il valore di fabbrica misurato su questa unità",
  "Risposta con orario — dedotto",
  "Non usare l'ora del servizio di localizzazione per correggere l'orologio del modulo — il valore di fabbrica misurato su questa unità",
  "Usare l'ora restituita dal servizio di localizzazione per correggere l'orologio del modulo — dedotto",
  ". Misurato il 2026-08-07: sia un token mancante sia uno non valido restituiscono questo stesso codice; il token va richiesto a Quectel e questa unità ne è priva",
  "Richiesta di localizzazione accettata",
  "(QuecLocator non ha alcun documento ufficiale nel ref/ di questo progetto, quindi il significato di questo codice resta da confermare)",
  "(il modulo lo maschera con * in lettura; senza token impostato AT+QLBS risponde 702)",
  "(l'ordine dipende da AT+QLBSCFG=\"latorder\"; senza token questa unità non ha permesso di verificarlo, quindi la corrispondenza dei campi resta da confermare)"],
 'ru-RU': [
  "Сетевое позиционирование без спутников: модуль отправляет в облако Quectel видимые точки доступа Wi-Fi и базовые станции и получает координаты — поэтому работает и в помещении. ⚠ Нужен токен от Quectel; на этом экземпляре он с завода пуст, а без него ответ всегда 702. ⚠ По QuecLocator в ref/ этого проекта нет ни одного официального документа, поэтому ниже изложено только измеренное 2026-08-07; всё предположительное помечено особо",
  "Вывести семь пунктов настройки и их диапазоны (без трафика)",
  "Задать токен QuecLocator (его надо запросить у Quectel)",
  "⚠ На этом экземпляре с завода пуст; без него AT+QLBS всегда отвечает 702 (измерено 2026-08-07 — выдуманная строка тоже даёт 702). После установки при чтении видны только *, точно как с паролем FTP",
  "строка, выданная Quectel",
  "Прочитать текущий токен (возвращается замаскированным звёздочками)",
  "Прочитать сервер позиционирования (на этом экземпляре с завода www.queclocator.com:80)",
  "Изменить адрес сервера позиционирования",
  "Сервер",
  "Формат «хост:порт». Заводское значение этого экземпляра именно такое, так что не трогайте его, если Quectel не укажет иное",
  "Прочитать тайм-аут запроса (на этом экземпляре с завода 60 секунд)",
  "Задать тайм-аут запроса в секундах",
  "Тайм-аут (с)",
  "Диапазон 10-120 (так возвращает AT+QLBSCFG=?), с завода 60 на этом экземпляре",
  "Прочитать синхронный / асинхронный режим (с завода 0 на этом экземпляре)",
  "Переключить синхронный и асинхронный режим",
  "0 — синхронный (команда ждёт результата); 1 — асинхронный (сначала возвращается OK, результат приходит отдельно). ⚠ Оба значения выведены из названия пункта — без токена на этом экземпляре их не проверить",
  "Прочитать порядок вывода широты и долготы. ⚠ Задаётся ключом в нижнем регистре latorder, но модуль возвращает его в верблюжьей записи latOrder",
  "Прочитать, содержит ли ответ отметку времени (возвращается как withTime, с завода 0 на этом экземпляре)",
  "Прочитать, корректирует ли результат позиционирования часы модуля (возвращается как timeUpdate, с завода 0 на этом экземпляре)",
  "Выполнить сетевое позиционирование. ⚠ Нужны токен и активный контекст PDP, расходуется трафик. Это единственный способ определения места, работающий в помещении, — он не использует спутники",
  "Вывести семь пунктов настройки QuecLocator с диапазонами (без трафика, в эфир ничего не уходит). Измерено на этом экземпляре 2026-08-07: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "Задать токен QuecLocator. ⚠ Эту строку надо запросить у Quectel; на этом экземпляре её нет, а без неё AT+QLBS всегда отвечает 702 (измерено 2026-08-07, выдуманный токен тоже даёт 702). При чтении видны только *",
  "Прочитать текущее значение этого пункта QuecLocator (без трафика)",
  "Задать пункт настройки QuecLocator (без трафика; настройка сохраняется в модуле)",
  "Выполнить сетевое позиционирование: модуль отправляет в облако QuecLocator видимые точки доступа Wi-Fi и базовые станции и получает координаты. ⚠ Нужны токен и активный контекст PDP, расходуется трафик. Это единственный способ определения места, работающий в помещении: спутники не нужны, поэтому он работает и там, где GNSS ничего не видит",
  "Токен QuecLocator = {0}",
  "Сетевое позиционирование не удалось — ошибка {0}",
  "Сетевое позиционирование не удалось — ошибка {0}: {1}",
  "Сетевое позиционирование выполнено, возвращённые поля: {0}",
  "Синхронно — команда ждёт результата; предположение, и 0 — заводское значение этого экземпляра",
  "Асинхронно — сначала возвращается OK, координаты приходят отдельно; предположение",
  "Порядок по умолчанию — заводское значение, измеренное на этом экземпляре",
  "Широта и долгота переставлены — предположение",
  "Ответ без отметки времени — заводское значение, измеренное на этом экземпляре",
  "Ответ с отметкой времени — предположение",
  "Не использовать время сервиса позиционирования для коррекции часов модуля — заводское значение, измеренное на этом экземпляре",
  "Использовать время, возвращённое сервисом позиционирования, для коррекции часов модуля — предположение",
  ". Измерено 2026-08-07: и отсутствующий, и неверный токен дают этот же код; токен запрашивается у Quectel, а на этом экземпляре его нет",
  "Запрос на позиционирование принят",
  "(по QuecLocator в ref/ этого проекта нет официального документа, поэтому значение этого кода не подтверждено)",
  "(при чтении модуль маскирует его звёздочками; если токен не задан, AT+QLBS отвечает 702)",
  "(порядок зависит от AT+QLBSCFG=\"latorder\"; без токена на этом экземпляре проверить не удалось, поэтому соответствие полей не подтверждено)"],
 'vi-VN': [
  "Định vị qua mạng, không cần vệ tinh: module gửi các điểm phát Wi-Fi và trạm phát sóng nó nhìn thấy lên đám mây của Quectel rồi nhận lại toạ độ, nên trong nhà vẫn dùng được. ⚠ Cần token do Quectel cấp; máy này xuất xưởng không có, và thiếu token thì luôn trả về 702. ⚠ QuecLocator không có tài liệu chính thức nào trong ref/ của dự án này, nên phần dưới chỉ ghi những gì đo được ngày 2026-08-07; chỗ nào là suy đoán đều có ghi rõ",
  "Liệt kê bảy mục cấu hình và khoảng giá trị (không tốn lưu lượng)",
  "Đặt token QuecLocator (phải xin từ Quectel)",
  "⚠ Máy này xuất xưởng để trống; thiếu nó thì AT+QLBS luôn trả về 702 (đo ngày 2026-08-07 — điền chuỗi bịa cũng ra 702). Đặt xong, khi đọc lại chỉ thấy dấu *, y như mật khẩu FTP",
  "chuỗi do Quectel cấp",
  "Xem token hiện tại (trả về đã che bằng dấu *)",
  "Xem máy chủ định vị (máy này xuất xưởng là www.queclocator.com:80)",
  "Đổi địa chỉ máy chủ định vị",
  "Máy chủ",
  "Định dạng «máy chủ:cổng». Giá trị xuất xưởng của máy này đúng là như vậy, nên đừng đổi trừ khi Quectel yêu cầu",
  "Xem thời gian chờ truy vấn (máy này xuất xưởng là 60 giây)",
  "Đặt thời gian chờ truy vấn, tính bằng giây",
  "Thời gian chờ (giây)",
  "Khoảng 10-120 (theo đúng những gì AT+QLBSCFG=? trả về), máy này xuất xưởng là 60",
  "Xem chế độ đồng bộ / bất đồng bộ (máy này xuất xưởng là 0)",
  "Chuyển giữa đồng bộ và bất đồng bộ",
  "0＝đồng bộ (lệnh chờ đến khi có kết quả), 1＝bất đồng bộ (trả OK trước, kết quả gửi riêng sau). ⚠ Hai nghĩa này suy ra từ tên mục, máy này không có token nên chưa kiểm chứng được",
  "Xem thứ tự xuất vĩ độ và kinh độ. ⚠ Khi đặt thì khoá viết thường là latorder, nhưng module đọc lại thành latOrder kiểu lạc đà",
  "Xem phản hồi có kèm thời gian hay không (đọc lại là withTime, máy này xuất xưởng là 0)",
  "Xem có dùng kết quả định vị để chỉnh đồng hồ module hay không (đọc lại là timeUpdate, máy này xuất xưởng là 0)",
  "Chạy định vị qua mạng. ⚠ Cần token và PDP context đang hoạt động, và sẽ tốn lưu lượng. Đây là cách định vị duy nhất dùng được trong nhà — nó không dựa vào vệ tinh",
  "Liệt kê bảy mục cấu hình của QuecLocator kèm khoảng giá trị (không tốn lưu lượng, không phát sóng). Đo trên máy này ngày 2026-08-07: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "Đặt token QuecLocator. ⚠ Chuỗi này phải xin từ Quectel; máy này xuất xưởng không có, và thiếu nó thì AT+QLBS luôn trả về 702 (đo ngày 2026-08-07, token bịa cũng ra 702). Khi đọc lại chỉ thấy dấu *",
  "Xem giá trị hiện tại của mục cấu hình QuecLocator đó (không tốn lưu lượng)",
  "Đặt một mục cấu hình QuecLocator (không tốn lưu lượng; thiết lập được lưu trong module)",
  "Chạy định vị qua mạng: module gửi các điểm phát Wi-Fi và trạm phát sóng nó nhìn thấy lên đám mây QuecLocator rồi nhận lại toạ độ. ⚠ Cần token và PDP context đang hoạt động, và sẽ tốn lưu lượng. Đây là cách định vị duy nhất dùng được trong nhà — không cần vệ tinh, nên chỗ nào GNSS không thấy gì nó vẫn định được",
  "Token QuecLocator = {0}",
  "Định vị qua mạng thất bại — lỗi {0}",
  "Định vị qua mạng thất bại — lỗi {0}: {1}",
  "Định vị qua mạng thành công, các trường trả về: {0}",
  "Đồng bộ — lệnh chờ đến khi có kết quả; suy đoán, và 0 chính là giá trị xuất xưởng của máy này",
  "Bất đồng bộ — trả OK trước, kết quả định vị gửi riêng sau; suy đoán",
  "Thứ tự mặc định — giá trị xuất xưởng đo được trên máy này",
  "Đảo vĩ độ và kinh độ — suy đoán",
  "Phản hồi không kèm thời gian — giá trị xuất xưởng đo được trên máy này",
  "Phản hồi có kèm thời gian — suy đoán",
  "Không dùng thời gian của dịch vụ định vị để chỉnh đồng hồ module — giá trị xuất xưởng đo được trên máy này",
  "Dùng thời gian dịch vụ định vị trả về để chỉnh đồng hồ module — suy đoán",
  ". Đo ngày 2026-08-07: không đặt token hay token sai đều trả về cùng mã này; token phải xin từ Quectel, còn máy này xuất xưởng để trống",
  "Yêu cầu định vị đã được tiếp nhận",
  "(QuecLocator không có tài liệu chính thức trong ref/ của dự án này, nên ý nghĩa của mã này chưa xác nhận được)",
  "(module che bằng dấu * khi đọc lại; chưa đặt token thì AT+QLBS trả về 702)",
  "(thứ tự chịu ảnh hưởng của AT+QLBSCFG=\"latorder\"; máy này không có token nên chưa đo được, việc ứng với trường nào vẫn chưa xác nhận)"],
 'id-ID': [
  "Penentuan posisi lewat jaringan tanpa satelit: modul mengirim titik akses Wi-Fi dan menara seluler yang terlihat ke awan Quectel lalu menerima koordinat, jadi di dalam ruangan pun bisa dipakai. ⚠ Perlu token dari Quectel; unit ini datang tanpa token, dan tanpa itu jawabannya selalu 702. ⚠ QuecLocator tidak punya dokumen resmi di ref/ proyek ini, jadi yang tertulis di bawah hanya yang terukur pada 2026-08-07; bagian yang merupakan dugaan sudah ditandai",
  "Menampilkan tujuh subitem konfigurasi beserta rentangnya (tanpa kuota)",
  "Menetapkan token QuecLocator (harus diminta ke Quectel)",
  "⚠ Kosong dari pabrik pada unit ini; tanpa token AT+QLBS selalu menjawab 702 (terukur 2026-08-07 — string karangan pun menghasilkan 702). Setelah disetel, saat dibaca hanya tampak *, persis seperti kata sandi FTP",
  "string yang diterbitkan Quectel",
  "Membaca token saat ini (kembali tersamar dengan *)",
  "Membaca server penentuan posisi (unit ini datang dengan www.queclocator.com:80)",
  "Mengubah alamat server penentuan posisi",
  "Server",
  "Formatnya «host:port». Nilai pabrik unit ini persis itu, jadi jangan diubah kecuali Quectel menyuruh lain",
  "Membaca batas waktu kueri (unit ini datang dengan 60 detik)",
  "Menetapkan batas waktu kueri dalam detik",
  "Batas waktu (detik)",
  "Rentang 10-120 (sesuai yang dikembalikan AT+QLBSCFG=?), 60 dari pabrik pada unit ini",
  "Membaca mode sinkron / asinkron (0 dari pabrik pada unit ini)",
  "Beralih antara sinkron dan asinkron",
  "0 = sinkron (perintah menunggu hasilnya); 1 = asinkron (OK keluar dulu, hasilnya menyusul terpisah). ⚠ Kedua makna ini disimpulkan dari nama subitemnya — tanpa token unit ini tidak bisa membuktikannya",
  "Membaca urutan keluaran lintang dan bujur. ⚠ Menyetelnya memakai kunci huruf kecil latorder, tetapi modul membacanya kembali sebagai latOrder bergaya unta",
  "Membaca apakah respons membawa waktu (dibaca kembali sebagai withTime, 0 dari pabrik pada unit ini)",
  "Membaca apakah hasil penentuan posisi dipakai membetulkan jam modul (dibaca kembali sebagai timeUpdate, 0 dari pabrik pada unit ini)",
  "Menjalankan penentuan posisi lewat jaringan. ⚠ Perlu token dan PDP context yang aktif, serta memakan kuota. Ini satu-satunya cara penentuan posisi yang jalan di dalam ruangan — ia tidak memakai satelit",
  "Menampilkan tujuh subitem konfigurasi QuecLocator beserta rentangnya (tanpa kuota, tidak ada yang keluar lewat udara). Terukur pada unit ini 2026-08-07: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "Menetapkan token QuecLocator. ⚠ String ini harus diminta ke Quectel; unit ini datang tanpa itu, dan tanpanya AT+QLBS selalu menjawab 702 (terukur 2026-08-07, token karangan pun 702). Saat dibaca hanya tampak *",
  "Membaca nilai subitem QuecLocator tersebut saat ini (tanpa kuota)",
  "Menetapkan subitem QuecLocator (tanpa kuota; setelan tersimpan di dalam modul)",
  "Menjalankan penentuan posisi lewat jaringan: modul mengirim titik akses Wi-Fi dan menara seluler yang terlihat ke awan QuecLocator lalu menerima koordinat. ⚠ Perlu token dan PDP context yang aktif, serta memakan kuota. Ini satu-satunya cara penentuan posisi yang jalan di dalam ruangan — tanpa satelit, jadi tetap bekerja di tempat yang GNSS-nya tidak melihat apa-apa",
  "Token QuecLocator = {0}",
  "Penentuan posisi lewat jaringan gagal — galat {0}",
  "Penentuan posisi lewat jaringan gagal — galat {0}: {1}",
  "Penentuan posisi lewat jaringan berhasil, ruas yang dikembalikan: {0}",
  "Sinkron — perintah menunggu hasilnya; dugaan, dan 0 memang nilai pabrik unit ini",
  "Asinkron — OK keluar dulu, hasil posisinya menyusul terpisah; dugaan",
  "Urutan bawaan — nilai pabrik yang terukur pada unit ini",
  "Lintang dan bujur ditukar — dugaan",
  "Respons tanpa waktu — nilai pabrik yang terukur pada unit ini",
  "Respons dengan waktu — dugaan",
  "Jangan pakai waktu dari layanan penentuan posisi untuk membetulkan jam modul — nilai pabrik yang terukur pada unit ini",
  "Pakai waktu yang dikembalikan layanan penentuan posisi untuk membetulkan jam modul — dugaan",
  ". Terukur 2026-08-07: token yang tidak disetel maupun token yang salah sama-sama menghasilkan kode ini; token diminta ke Quectel dan unit ini datang tanpa itu",
  "Permintaan penentuan posisi diterima",
  "(QuecLocator tidak punya dokumen resmi di ref/ proyek ini, jadi arti kode ini belum dipastikan)",
  "(modul menyamarkannya dengan * saat dibaca; kalau token belum disetel AT+QLBS menjawab 702)",
  "(urutannya dipengaruhi AT+QLBSCFG=\"latorder\"; tanpa token unit ini tidak bisa mengujinya, jadi pemetaan ruasnya belum dipastikan)"],
 'ms-MY': [
  "Penentuan kedudukan melalui rangkaian tanpa satelit: modul menghantar titik akses Wi-Fi dan menara selular yang dilihatnya ke awan Quectel lalu menerima koordinat, jadi di dalam bangunan pun boleh digunakan. ⚠ Ia memerlukan token daripada Quectel; unit ini keluar kilang tanpa token, dan tanpanya jawapannya sentiasa 702. ⚠ QuecLocator tiada sebarang dokumen rasmi dalam ref/ projek ini, jadi yang tertulis di bawah hanyalah apa yang diukur pada 2026-08-07; bahagian yang merupakan andaian sudah ditandakan",
  "Senaraikan tujuh subitem tetapan berserta julatnya (tanpa kuota)",
  "Tetapkan token QuecLocator (perlu dipohon daripada Quectel)",
  "⚠ Kosong dari kilang pada unit ini; tanpanya AT+QLBS sentiasa menjawab 702 (diukur 2026-08-07 — rentetan rekaan pun menghasilkan 702). Selepas ditetapkan, bacaan semula hanya memaparkan *, persis seperti kata laluan FTP",
  "rentetan yang dikeluarkan oleh Quectel",
  "Baca token semasa (dipulangkan bertopeng dengan *)",
  "Baca pelayan penentuan kedudukan (unit ini keluar kilang dengan www.queclocator.com:80)",
  "Tukar alamat pelayan penentuan kedudukan",
  "Pelayan",
  "Formatnya «hos:port». Nilai kilang unit ini memang itu, jadi jangan diubah melainkan Quectel menetapkan sebaliknya",
  "Baca had masa pertanyaan (unit ini keluar kilang dengan 60 saat)",
  "Tetapkan had masa pertanyaan dalam saat",
  "Had masa (saat)",
  "Julat 10-120 (sebagaimana dipulangkan AT+QLBSCFG=?), 60 dari kilang pada unit ini",
  "Baca mod segerak / tak segerak (0 dari kilang pada unit ini)",
  "Tukar antara segerak dan tak segerak",
  "0 = segerak (arahan menunggu keputusan); 1 = tak segerak (OK keluar dahulu, keputusan menyusul berasingan). ⚠ Kedua-dua makna ini disimpulkan daripada nama subitem — tanpa token unit ini tidak dapat mengesahkannya",
  "Baca susunan keluaran latitud dan longitud. ⚠ Ia ditetapkan dengan kunci huruf kecil latorder, tetapi modul membacanya semula sebagai latOrder bergaya unta",
  "Baca sama ada maklum balas membawa masa (dibaca semula sebagai withTime, 0 dari kilang pada unit ini)",
  "Baca sama ada keputusan kedudukan digunakan untuk membetulkan jam modul (dibaca semula sebagai timeUpdate, 0 dari kilang pada unit ini)",
  "Jalankan penentuan kedudukan melalui rangkaian. ⚠ Memerlukan token dan PDP context yang aktif, serta memakan kuota. Ini satu-satunya kaedah penentuan kedudukan yang berfungsi di dalam bangunan — ia tidak menggunakan satelit",
  "Senaraikan tujuh subitem tetapan QuecLocator berserta julatnya (tanpa kuota, tiada apa-apa keluar melalui udara). Diukur pada unit ini 2026-08-07: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "Tetapkan token QuecLocator. ⚠ Rentetan ini perlu dipohon daripada Quectel; unit ini keluar kilang tanpanya, dan tanpanya AT+QLBS sentiasa menjawab 702 (diukur 2026-08-07, token rekaan pun 702). Bacaan semula hanya memaparkan *",
  "Baca nilai semasa subitem QuecLocator berkenaan (tanpa kuota)",
  "Tetapkan subitem QuecLocator (tanpa kuota; tetapan disimpan dalam modul)",
  "Jalankan penentuan kedudukan melalui rangkaian: modul menghantar titik akses Wi-Fi dan menara selular yang dilihatnya ke awan QuecLocator lalu menerima koordinat. ⚠ Memerlukan token dan PDP context yang aktif, serta memakan kuota. Ini satu-satunya kaedah yang berfungsi di dalam bangunan — tanpa satelit, jadi ia tetap berfungsi di tempat GNSS tidak nampak apa-apa",
  "Token QuecLocator = {0}",
  "Penentuan kedudukan melalui rangkaian gagal — ralat {0}",
  "Penentuan kedudukan melalui rangkaian gagal — ralat {0}: {1}",
  "Penentuan kedudukan melalui rangkaian berjaya, medan yang dipulangkan: {0}",
  "Segerak — arahan menunggu keputusan; andaian, dan 0 memang nilai kilang unit ini",
  "Tak segerak — OK keluar dahulu, kedudukan menyusul berasingan; andaian",
  "Susunan lalai — nilai kilang yang diukur pada unit ini",
  "Latitud dan longitud bertukar tempat — andaian",
  "Maklum balas tanpa masa — nilai kilang yang diukur pada unit ini",
  "Maklum balas dengan masa — andaian",
  "Jangan guna masa daripada perkhidmatan kedudukan untuk membetulkan jam modul — nilai kilang yang diukur pada unit ini",
  "Guna masa yang dipulangkan perkhidmatan kedudukan untuk membetulkan jam modul — andaian",
  ". Diukur 2026-08-07: token yang tidak ditetapkan mahupun token yang tidak sah sama-sama menghasilkan kod ini; token dipohon daripada Quectel dan unit ini keluar kilang tanpanya",
  "Permintaan penentuan kedudukan diterima",
  "(QuecLocator tiada dokumen rasmi dalam ref/ projek ini, jadi maksud kod ini belum disahkan)",
  "(modul menyamarkannya dengan * semasa dibaca; jika token belum ditetapkan AT+QLBS menjawab 702)",
  "(susunannya dipengaruhi AT+QLBSCFG=\"latorder\"; tanpa token unit ini tidak dapat mengujinya, jadi padanan medan belum disahkan)"],
 'th-TH': [
  "การหาตำแหน่งผ่านเครือข่ายโดยไม่ใช้ดาวเทียม: โมดูลส่งข้อมูลจุดกระจายสัญญาณ Wi-Fi และเสาสัญญาณที่มองเห็นไปยังคลาวด์ของ Quectel แล้วรับพิกัดกลับมา จึงใช้งานในอาคารได้ ⚠ ต้องมี token ที่ Quectel ออกให้ เครื่องนี้ออกจากโรงงานมาว่างเปล่า และถ้าไม่มีจะตอบ 702 เสมอ ⚠ QuecLocator ไม่มีเอกสารทางการอยู่ใน ref/ ของโปรเจกต์นี้เลย ข้อความข้างล่างจึงเขียนเฉพาะสิ่งที่วัดได้จริงเมื่อ 2026-08-07 ส่วนที่เป็นการคาดเดามีระบุไว้ชัดเจน",
  "แสดงรายการเจ็ดหัวข้อการตั้งค่าพร้อมช่วงค่า (ไม่กินปริมาณการใช้งาน)",
  "ตั้งค่า token ของ QuecLocator (ต้องขอจาก Quectel)",
  "⚠ เครื่องนี้ออกจากโรงงานมาว่างเปล่า ถ้าไม่มีจะทำให้ AT+QLBS ตอบ 702 เสมอ (วัดเมื่อ 2026-08-07 ใส่ข้อความมั่ว ๆ ก็ได้ 702 เหมือนกัน) เมื่อตั้งค่าแล้วอ่านกลับจะเห็นแต่ * เหมือนรหัสผ่าน FTP เป๊ะ",
  "ข้อความที่ Quectel ออกให้",
  "อ่าน token ปัจจุบัน (จะถูกปิดบังด้วย *)",
  "อ่านเซิร์ฟเวอร์หาตำแหน่ง (เครื่องนี้ออกจากโรงงานเป็น www.queclocator.com:80)",
  "เปลี่ยนที่อยู่เซิร์ฟเวอร์หาตำแหน่ง",
  "เซิร์ฟเวอร์",
  "รูปแบบคือ «โฮสต์:พอร์ต» ค่าจากโรงงานของเครื่องนี้ก็คือค่านี้พอดี ดังนั้นอย่าไปแก้ นอกจาก Quectel จะระบุเป็นอย่างอื่น",
  "อ่านเวลารอของการสอบถาม (เครื่องนี้ออกจากโรงงานเป็น 60 วินาที)",
  "ตั้งเวลารอของการสอบถามเป็นวินาที",
  "เวลารอ (วินาที)",
  "ช่วง 10-120 (ตามที่ AT+QLBSCFG=? ตอบกลับจริง) เครื่องนี้ออกจากโรงงานเป็น 60",
  "อ่านโหมดซิงโครนัส / อะซิงโครนัส (เครื่องนี้ออกจากโรงงานเป็น 0)",
  "สลับระหว่างซิงโครนัสกับอะซิงโครนัส",
  "0＝ซิงโครนัส (คำสั่งรอจนได้ผลลัพธ์), 1＝อะซิงโครนัส (ตอบ OK ก่อน ผลลัพธ์ตามมาทีหลังแยกต่างหาก) ⚠ ความหมายสองค่านี้อนุมานจากชื่อหัวข้อ เครื่องนี้ไม่มี token จึงยังพิสูจน์ไม่ได้",
  "อ่านลำดับการแสดงละติจูดกับลองจิจูด ⚠ ตอนตั้งค่าใช้คีย์ตัวพิมพ์เล็ก latorder แต่โมดูลอ่านกลับมาเป็น latOrder แบบอูฐ",
  "อ่านว่าการตอบกลับมีเวลาแนบมาด้วยหรือไม่ (อ่านกลับเป็น withTime เครื่องนี้ออกจากโรงงานเป็น 0)",
  "อ่านว่าใช้ผลการหาตำแหน่งไปปรับนาฬิกาของโมดูลหรือไม่ (อ่านกลับเป็น timeUpdate เครื่องนี้ออกจากโรงงานเป็น 0)",
  "สั่งหาตำแหน่งผ่านเครือข่าย ⚠ ต้องมี token และ PDP context ที่เปิดใช้งานแล้ว และจะกินปริมาณการใช้งาน นี่คือวิธีหาตำแหน่งวิธีเดียวที่ใช้ได้ในอาคาร เพราะไม่พึ่งดาวเทียม",
  "แสดงรายการเจ็ดหัวข้อการตั้งค่าของ QuecLocator พร้อมช่วงค่า (ไม่กินปริมาณการใช้งาน ไม่ออกอากาศ) วัดบนเครื่องนี้เมื่อ 2026-08-07: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "ตั้งค่า token ของ QuecLocator ⚠ ข้อความนี้ต้องขอจาก Quectel เครื่องนี้ออกจากโรงงานมาว่างเปล่า และถ้าไม่มี AT+QLBS จะตอบ 702 เสมอ (วัดเมื่อ 2026-08-07 ใส่ token มั่ว ๆ ก็ได้ 702) อ่านกลับจะเห็นแต่ *",
  "อ่านค่าปัจจุบันของหัวข้อ QuecLocator นั้น (ไม่กินปริมาณการใช้งาน)",
  "ตั้งค่าหัวข้อของ QuecLocator (ไม่กินปริมาณการใช้งาน ค่าจะถูกเก็บไว้ในโมดูล)",
  "สั่งหาตำแหน่งผ่านเครือข่าย: โมดูลส่งข้อมูลจุดกระจายสัญญาณ Wi-Fi และเสาสัญญาณที่มองเห็นไปยังคลาวด์ QuecLocator แล้วรับพิกัดกลับมา ⚠ ต้องมี token และ PDP context ที่เปิดใช้งานแล้ว และจะกินปริมาณการใช้งาน นี่คือวิธีหาตำแหน่งวิธีเดียวที่ใช้ได้ในอาคาร เพราะไม่พึ่งดาวเทียม ที่ไหนที่ GNSS มองไม่เห็นอะไรเลย วิธีนี้ก็ยังหาตำแหน่งได้",
  "token ของ QuecLocator = {0}",
  "หาตำแหน่งผ่านเครือข่ายล้มเหลว — ข้อผิดพลาด {0}",
  "หาตำแหน่งผ่านเครือข่ายล้มเหลว — ข้อผิดพลาด {0}: {1}",
  "หาตำแหน่งผ่านเครือข่ายสำเร็จ ฟิลด์ที่ตอบกลับ: {0}",
  "ซิงโครนัส — คำสั่งรอจนได้ผลลัพธ์ เป็นการคาดเดา และค่าจากโรงงานของเครื่องนี้ก็คือ 0 นี่เอง",
  "อะซิงโครนัส — ตอบ OK ก่อน ผลการหาตำแหน่งตามมาทีหลังแยกต่างหาก เป็นการคาดเดา",
  "ลำดับเริ่มต้น — ค่าจากโรงงานที่วัดได้บนเครื่องนี้",
  "สลับละติจูดกับลองจิจูด — เป็นการคาดเดา",
  "การตอบกลับไม่มีเวลาแนบมา — ค่าจากโรงงานที่วัดได้บนเครื่องนี้",
  "การตอบกลับมีเวลาแนบมาด้วย — เป็นการคาดเดา",
  "ไม่ใช้เวลาจากบริการหาตำแหน่งมาปรับนาฬิกาโมดูล — ค่าจากโรงงานที่วัดได้บนเครื่องนี้",
  "ใช้เวลาที่บริการหาตำแหน่งตอบกลับมาปรับนาฬิกาโมดูล — เป็นการคาดเดา",
  " วัดเมื่อ 2026-08-07: ไม่ว่าจะไม่ได้ตั้ง token หรือ token ไม่ถูกต้อง ก็ได้รหัสนี้เหมือนกัน token ต้องขอจาก Quectel และเครื่องนี้ออกจากโรงงานมาว่างเปล่า",
  "รับคำขอหาตำแหน่งแล้ว",
  "(QuecLocator ไม่มีเอกสารทางการอยู่ใน ref/ ของโปรเจกต์นี้ ความหมายของรหัสนี้จึงยังไม่ได้รับการยืนยัน)",
  "(โมดูลจะปิดบังด้วย * เมื่ออ่านกลับ ถ้ายังไม่ได้ตั้ง token คำสั่ง AT+QLBS จะตอบ 702)",
  "(ลำดับขึ้นกับ AT+QLBSCFG=\"latorder\" เครื่องนี้ไม่มี token จึงยังทดสอบไม่ได้ การจับคู่ฟิลด์จึงยังไม่ได้รับการยืนยัน)"],
 'hi-IN': [
  "उपग्रह के बिना नेटवर्क से स्थान निर्धारण: मॉड्यूल जो Wi-Fi हॉटस्पॉट और सेल टावर देखता है, उनकी जानकारी Quectel के क्लाउड को भेजकर निर्देशांक पा लेता है — इसलिए यह घर के भीतर भी चलता है। ⚠ इसके लिए Quectel का token चाहिए; यह इकाई बिना token के आती है, और उसके बिना उत्तर हमेशा 702 रहता है। ⚠ QuecLocator का कोई आधिकारिक दस्तावेज़ इस परियोजना के ref/ में नहीं है, इसलिए नीचे केवल वही लिखा है जो 2026-08-07 को मापा गया; जो अनुमान है उस पर निशान लगा है",
  "सातों कॉन्फ़िगरेशन उप-मदों और उनकी सीमाएँ सूचीबद्ध करें (कोई डेटा खर्च नहीं)",
  "QuecLocator का token सेट करें (Quectel से माँगना पड़ता है)",
  "⚠ इस इकाई में फ़ैक्टरी से ख़ाली; इसके बिना AT+QLBS हमेशा 702 लौटाता है (2026-08-07 को मापा गया — मनगढ़ंत स्ट्रिंग से भी 702 ही आता है)। सेट करने के बाद पढ़ने पर केवल * दिखते हैं, ठीक FTP पासवर्ड की तरह",
  "Quectel द्वारा जारी की गई स्ट्रिंग",
  "मौजूदा token पढ़ें (* से ढका हुआ लौटता है)",
  "स्थान-निर्धारण सर्वर पढ़ें (यह इकाई www.queclocator.com:80 के साथ आती है)",
  "स्थान-निर्धारण सर्वर का पता बदलें",
  "सर्वर",
  "प्रारूप «होस्ट:पोर्ट» है। इस इकाई का फ़ैक्टरी मान ठीक यही है, इसलिए Quectel के कहे बिना इसे न छेड़ें",
  "पूछताछ की समय-सीमा पढ़ें (यह इकाई 60 सेकंड के साथ आती है)",
  "पूछताछ की समय-सीमा सेकंड में सेट करें",
  "समय-सीमा (सेकंड)",
  "सीमा 10-120 (जैसा AT+QLBSCFG=? ने वास्तव में लौटाया), इस इकाई में फ़ैक्टरी से 60",
  "समकालिक / असमकालिक मोड पढ़ें (इस इकाई में फ़ैक्टरी से 0)",
  "समकालिक और असमकालिक के बीच बदलें",
  "0 = समकालिक (आदेश परिणाम की प्रतीक्षा करता है); 1 = असमकालिक (पहले OK आता है, परिणाम अलग से बाद में)। ⚠ ये दोनों अर्थ उप-मद के नाम से अनुमानित हैं — token के बिना इस इकाई पर इनकी पुष्टि नहीं हो सकी",
  "अक्षांश-देशांतर की आउटपुट क्रम पढ़ें। ⚠ सेट करते समय कुंजी छोटे अक्षरों में latorder है, पर मॉड्यूल उसे ऊँट-शैली latOrder के रूप में लौटाता है",
  "पढ़ें कि उत्तर में समय आता है या नहीं (withTime के रूप में लौटता है, इस इकाई में फ़ैक्टरी से 0)",
  "पढ़ें कि स्थान-परिणाम से मॉड्यूल की घड़ी सुधारी जाती है या नहीं (timeUpdate के रूप में लौटता है, इस इकाई में फ़ैक्टरी से 0)",
  "नेटवर्क से स्थान निर्धारण चलाएँ। ⚠ token और सक्रिय PDP context चाहिए, और डेटा खर्च होता है। घर के भीतर काम करने वाला यही एकमात्र तरीक़ा है — यह उपग्रहों का उपयोग नहीं करता",
  "QuecLocator के सातों कॉन्फ़िगरेशन उप-मद और उनकी सीमाएँ सूचीबद्ध करें (कोई डेटा खर्च नहीं, हवा में कुछ नहीं जाता)। इस इकाई पर 2026-08-07 को मापा गया: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "QuecLocator का token सेट करें। ⚠ यह स्ट्रिंग Quectel से माँगनी पड़ती है; यह इकाई इसके बिना आती है, और इसके बिना AT+QLBS हमेशा 702 लौटाता है (2026-08-07 को मापा गया, मनगढ़ंत token से भी 702)। पढ़ने पर केवल * दिखते हैं",
  "उस QuecLocator उप-मद का मौजूदा मान पढ़ें (कोई डेटा खर्च नहीं)",
  "QuecLocator का कोई उप-मद सेट करें (कोई डेटा खर्च नहीं; सेटिंग मॉड्यूल में सहेजी जाती है)",
  "नेटवर्क से स्थान निर्धारण चलाएँ: मॉड्यूल जो Wi-Fi हॉटस्पॉट और सेल टावर देखता है उन्हें QuecLocator के क्लाउड को भेजकर निर्देशांक पाता है। ⚠ token और सक्रिय PDP context चाहिए, और डेटा खर्च होता है। घर के भीतर काम करने वाला यही एकमात्र तरीक़ा है — उपग्रह लगते ही नहीं, इसलिए जहाँ GNSS को कुछ नहीं दिखता वहाँ भी यह चल जाता है",
  "QuecLocator का token = {0}",
  "नेटवर्क स्थान निर्धारण विफल — त्रुटि {0}",
  "नेटवर्क स्थान निर्धारण विफल — त्रुटि {0}: {1}",
  "नेटवर्क स्थान निर्धारण सफल, लौटाए गए क्षेत्र: {0}",
  "समकालिक — आदेश परिणाम की प्रतीक्षा करता है; अनुमान, और इस इकाई का फ़ैक्टरी मान यही 0 है",
  "असमकालिक — पहले OK आता है, स्थान बाद में अलग से; अनुमान",
  "डिफ़ॉल्ट क्रम — इस इकाई पर मापा गया फ़ैक्टरी मान",
  "अक्षांश और देशांतर आपस में बदले हुए — अनुमान",
  "उत्तर में समय नहीं — इस इकाई पर मापा गया फ़ैक्टरी मान",
  "उत्तर में समय भी — अनुमान",
  "मॉड्यूल की घड़ी सुधारने के लिए स्थान-सेवा का समय न लें — इस इकाई पर मापा गया फ़ैक्टरी मान",
  "मॉड्यूल की घड़ी सुधारने के लिए स्थान-सेवा का लौटाया समय लें — अनुमान",
  "। 2026-08-07 को मापा गया: token न होने और ग़लत token, दोनों पर यही कोड आता है; token Quectel से माँगना पड़ता है और यह इकाई उसके बिना आती है",
  "स्थान-निर्धारण का अनुरोध स्वीकृत",
  "(QuecLocator का कोई आधिकारिक दस्तावेज़ इस परियोजना के ref/ में नहीं है, इसलिए इस कोड का अर्थ अपुष्ट है)",
  "(पढ़ते समय मॉड्यूल इसे * से ढक देता है; token सेट न हो तो AT+QLBS 702 लौटाता है)",
  "(क्रम AT+QLBSCFG=\"latorder\" पर निर्भर है; token न होने से इस इकाई पर जाँच नहीं हो सकी, इसलिए किस क्षेत्र का क्या अर्थ है यह अपुष्ट है)"],
 'tr-TR': [
  "Uydusuz ağ konumlandırma: modül gördüğü Wi-Fi erişim noktalarını ve baz istasyonlarını Quectel bulutuna gönderip koordinat alır, dolayısıyla kapalı alanda da çalışır. ⚠ Quectel'den alınan bir token gerekir; bu cihaz tokensiz gelir ve token olmadan yanıt hep 702'dir. ⚠ QuecLocator'ın bu projenin ref/ dizininde hiçbir resmî belgesi yok, bu yüzden aşağıdakiler yalnızca 2026-08-07'de ölçülenleri aktarır; çıkarıma dayanan kısımlar ayrıca belirtilmiştir",
  "Yedi yapılandırma alt öğesini ve aralıklarını listeler (veri harcamaz)",
  "QuecLocator token'ını ayarlar (Quectel'den talep edilmesi gerekir)",
  "⚠ Bu cihazda fabrikadan boş gelir; o olmadan AT+QLBS hep 702 döndürür (2026-08-07'de ölçüldü — uydurma bir dizge de 702 verir). Ayarlandıktan sonra okunduğunda yalnızca * görünür, tıpkı FTP parolasında olduğu gibi",
  "Quectel'in verdiği dizge",
  "Geçerli token'ı okur (* ile maskelenmiş döner)",
  "Konumlandırma sunucusunu okur (bu cihaz www.queclocator.com:80 ile gelir)",
  "Konumlandırma sunucusunun adresini değiştirir",
  "Sunucu",
  "Biçim «konak:bağlantı noktası». Bu cihazın fabrika değeri tam olarak budur, Quectel aksini söylemedikçe dokunmayın",
  "Sorgu zaman aşımını okur (bu cihaz 60 saniyeyle gelir)",
  "Sorgu zaman aşımını saniye olarak ayarlar",
  "Zaman aşımı (sn)",
  "Aralık 10-120 (AT+QLBSCFG=? böyle döndürüyor), bu cihazda fabrikadan 60",
  "Eşzamanlı / eşzamansız kipi okur (bu cihazda fabrikadan 0)",
  "Eşzamanlı ile eşzamansız arasında geçiş yapar",
  "0 = eşzamanlı (komut sonucu bekler); 1 = eşzamansız (önce OK döner, sonuç ayrıca gelir). ⚠ Bu iki anlam alt öğenin adından çıkarılmıştır — token olmadan bu cihazda doğrulanamıyor",
  "Enlem/boylam çıkış sırasını okur. ⚠ Küçük harfli latorder anahtarıyla ayarlanır, ama modül bunu deve sırtı latOrder olarak geri okur",
  "Yanıtın zaman damgası taşıyıp taşımadığını okur (withTime olarak geri okunur, bu cihazda fabrikadan 0)",
  "Konum sonucunun modül saatini düzeltip düzeltmediğini okur (timeUpdate olarak geri okunur, bu cihazda fabrikadan 0)",
  "Ağ üzerinden konum belirler. ⚠ Token ve etkin bir PDP context gerekir, ayrıca veri harcar. Kapalı alanda çalışan tek konumlandırma yöntemi budur — uyduları kullanmaz",
  "QuecLocator'ın yedi yapılandırma alt öğesini aralıklarıyla listeler (veri harcamaz, havadan hiçbir şey gitmez). Bu cihazda 2026-08-07'de ölçüldü: asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "QuecLocator token'ını ayarlar. ⚠ Bu dizgeyi Quectel'den talep etmek gerekir; bu cihaz onsuz gelir ve onsuz AT+QLBS hep 702 döndürür (2026-08-07'de ölçüldü, uydurma token da 702 verir). Geri okunduğunda yalnızca * görünür",
  "İlgili QuecLocator alt öğesinin geçerli değerini okur (veri harcamaz)",
  "Bir QuecLocator alt öğesini ayarlar (veri harcamaz; ayar modülde saklanır)",
  "Ağ üzerinden konum belirler: modül gördüğü Wi-Fi erişim noktalarını ve baz istasyonlarını QuecLocator bulutuna gönderip koordinat alır. ⚠ Token ve etkin bir PDP context gerekir, ayrıca veri harcar. Kapalı alanda çalışan tek yöntem budur — uydu kullanmadığı için GNSS'in hiçbir şey görmediği yerde bile çalışır",
  "QuecLocator token = {0}",
  "Ağ konumlandırma başarısız — hata {0}",
  "Ağ konumlandırma başarısız — hata {0}: {1}",
  "Ağ konumlandırma başarılı, dönen alanlar: {0}",
  "Eşzamanlı — komut sonucu bekler; çıkarım, ve bu cihazın fabrika değeri zaten 0",
  "Eşzamansız — önce OK döner, konum ayrıca gelir; çıkarım",
  "Varsayılan sıra — bu cihazda ölçülen fabrika değeri",
  "Enlem ile boylam yer değiştirmiş — çıkarım",
  "Yanıtta zaman damgası yok — bu cihazda ölçülen fabrika değeri",
  "Yanıtta zaman damgası var — çıkarım",
  "Modül saatini düzeltmek için konum hizmetinin saatini kullanma — bu cihazda ölçülen fabrika değeri",
  "Modül saatini düzeltmek için konum hizmetinin döndürdüğü saati kullan — çıkarım",
  ". 2026-08-07'de ölçüldü: token'ın hiç ayarlanmaması da geçersiz olması da aynı bu kodu veriyor; token Quectel'den istenir ve bu cihaz onsuz gelir",
  "Konum isteği kabul edildi",
  "(QuecLocator'ın bu projenin ref/ dizininde resmî belgesi yok, bu yüzden bu kodun anlamı doğrulanmamıştır)",
  "(modül geri okurken * ile maskeler; token ayarlı değilse AT+QLBS 702 döndürür)",
  "(sıra AT+QLBSCFG=\"latorder\" ayarına bağlıdır; token olmadığı için bu cihazda sınanamadı, dolayısıyla alan eşlemesi doğrulanmamıştır)"],
 'ar-SA': [
  "تحديد المواقع عبر الشبكة بلا أقمار صناعية: يرسل الموديل ما يراه من نقاط وصول Wi-Fi وأبراج خلوية إلى سحابة Quectel فيستعيد الإحداثيات، ولذلك يعمل داخل المباني. ⚠ ويلزمه رمز token تصدره Quectel، والجهاز يخرج من المصنع بلا رمز، وبدونه يكون الرد دائماً 702. ⚠ ولا يوجد لـ QuecLocator أي مستند رسمي في مجلد ref/ بهذا المشروع، لذا لا يذكر ما يلي إلا ما قيس فعلاً في 2026-08-07، وما كان استنتاجاً فقد أُشير إليه صراحةً",
  "يسرد بنود الضبط السبعة ومدياتها (بلا استهلاك بيانات)",
  "يضبط رمز QuecLocator (يجب طلبه من Quectel)",
  "⚠ فارغ من المصنع في هذا الجهاز، وبدونه يردّ AT+QLBS دائماً بالرمز 702 (قيس في 2026-08-07 —— وحتى النص المُختلَق يعطي 702). وبعد ضبطه لا تظهر عند القراءة سوى علامات *، تماماً كما في كلمة مرور FTP",
  "النص الذي تصدره Quectel",
  "يقرأ الرمز الحالي (يعود مُخفى بعلامات *)",
  "يقرأ خادم تحديد المواقع (يخرج هذا الجهاز من المصنع بالقيمة www.queclocator.com:80)",
  "يغيّر عنوان خادم تحديد المواقع",
  "الخادم",
  "الصيغة «المضيف:المنفذ». وقيمة المصنع في هذا الجهاز هي هذه بالضبط، فلا تغيّرها ما لم تحدّد Quectel غير ذلك",
  "يقرأ مهلة الاستعلام (يخرج هذا الجهاز من المصنع بـ 60 ثانية)",
  "يضبط مهلة الاستعلام بالثواني",
  "المهلة (ثانية)",
  "المدى 10-120 (كما يعيده AT+QLBSCFG=? فعلاً)، وقيمة المصنع في هذا الجهاز 60",
  "يقرأ الوضع المتزامن / غير المتزامن (قيمة المصنع في هذا الجهاز 0)",
  "يبدّل بين المتزامن وغير المتزامن",
  "0 = متزامن (ينتظر الأمر النتيجة)، و1 = غير متزامن (يعود OK أولاً ثم تصل النتيجة منفصلةً لاحقاً). ⚠ وهذان المعنيان مستنتجان من اسم البند، ولا يمكن التحقق منهما في هذا الجهاز لعدم وجود رمز",
  "يقرأ ترتيب إخراج خط العرض وخط الطول. ⚠ ويُضبط بالمفتاح الصغير latorder، غير أن الموديل يعيده بصيغة السنام latOrder",
  "يقرأ هل يحمل الرد طابعاً زمنياً (يُعاد باسم withTime، وقيمة المصنع في هذا الجهاز 0)",
  "يقرأ هل تُصحَّح ساعة الموديل بنتيجة تحديد الموقع (يُعاد باسم timeUpdate، وقيمة المصنع في هذا الجهاز 0)",
  "ينفّذ تحديد موقع عبر الشبكة. ⚠ ويلزمه رمز token وسياق PDP مفعَّل، ويستهلك بيانات. وهو الأسلوب الوحيد الذي يعمل داخل المباني —— لأنه لا يستعمل الأقمار الصناعية",
  "يسرد بنود ضبط QuecLocator السبعة بمدياتها (بلا استهلاك بيانات، ولا يخرج شيء إلى الأثير). قيس في هذا الجهاز يوم 2026-08-07: ‏asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "يضبط رمز QuecLocator. ⚠ ويجب طلب هذا النص من Quectel، والجهاز يخرج من المصنع بدونه، وبدونه يردّ AT+QLBS دائماً بالرمز 702 (قيس في 2026-08-07، وحتى الرمز المُختلَق يعطي 702). وعند القراءة لا تظهر سوى علامات *",
  "يقرأ القيمة الحالية لذلك البند من ضبط QuecLocator (بلا استهلاك بيانات)",
  "يضبط بنداً من بنود QuecLocator (بلا استهلاك بيانات، ويُحفظ الضبط داخل الموديل)",
  "ينفّذ تحديد موقع عبر الشبكة: يرسل الموديل ما يراه من نقاط وصول Wi-Fi وأبراج خلوية إلى سحابة QuecLocator فيستعيد الإحداثيات. ⚠ ويلزمه رمز token وسياق PDP مفعَّل، ويستهلك بيانات. وهو الأسلوب الوحيد الذي يعمل داخل المباني —— فهو لا يحتاج أقماراً صناعية، ولذلك يعمل حتى حيث لا يرى GNSS شيئاً",
  "رمز QuecLocator = {0}",
  "أخفق تحديد الموقع عبر الشبكة —— الخطأ {0}",
  "أخفق تحديد الموقع عبر الشبكة —— الخطأ {0}: {1}",
  "نجح تحديد الموقع عبر الشبكة، والحقول المعادة: {0}",
  "متزامن —— ينتظر الأمر النتيجة؛ استنتاج، وقيمة المصنع في هذا الجهاز هي 0 نفسها",
  "غير متزامن —— يعود OK أولاً ثم يصل الموقع منفصلاً؛ استنتاج",
  "الترتيب الافتراضي —— قيمة المصنع المقيسة في هذا الجهاز",
  "تبديل خط العرض بخط الطول —— استنتاج",
  "الرد بلا طابع زمني —— قيمة المصنع المقيسة في هذا الجهاز",
  "الرد مع طابع زمني —— استنتاج",
  "عدم استعمال وقت خدمة تحديد المواقع لتصحيح ساعة الموديل —— قيمة المصنع المقيسة في هذا الجهاز",
  "استعمال الوقت الذي تعيده خدمة تحديد المواقع لتصحيح ساعة الموديل —— استنتاج",
  ". قيس في 2026-08-07: يعطي هذا الرمز نفسه سواءٌ لم يُضبط الرمز أصلاً أم كان غير صالح؛ والرمز يُطلب من Quectel والجهاز يخرج من المصنع بدونه",
  "قُبل طلب تحديد الموقع",
  "(لا يوجد لـ QuecLocator مستند رسمي في مجلد ref/ بهذا المشروع، فمعنى هذا الرمز غير مؤكَّد)",
  "(يخفيه الموديل بعلامات * عند القراءة؛ وإن لم يُضبط الرمز ردّ AT+QLBS بالرمز 702)",
  "(يتأثر الترتيب بـ AT+QLBSCFG=\"latorder\"؛ ولعدم وجود رمز لم يمكن التحقق في هذا الجهاز، فمطابقة الحقول غير مؤكَّدة)"],
 'he-IL': [
  "איכון רשת בלי לוויינים: המודול שולח לענן של Quectel את נקודות ה-Wi-Fi והתאים הסלולריים שהוא רואה ומקבל בחזרה קואורדינטות, ולכן זה עובד גם בתוך מבנה. ⚠ נדרש token מ-Quectel; היחידה הזו מגיעה בלעדיו, ובלעדיו התשובה תמיד 702. ⚠ ל-QuecLocator אין שום מסמך רשמי ב-ref/ של הפרויקט הזה, ולכן כל מה שלהלן מדווח רק את מה שנמדד ב-2026-08-07; מה שהוא הסקה מסומן ככזה",
  "הצגת שבעת פריטי התצורה והטווחים שלהם (ללא צריכת תעבורה)",
  "הגדרת ה-token של QuecLocator (יש לבקש אותו מ-Quectel)",
  "⚠ ריק מהיצרן ביחידה הזו; בלעדיו AT+QLBS משיב תמיד 702 (נמדד ב-2026-08-07 — גם מחרוזת מומצאת מחזירה 702). לאחר ההגדרה, בקריאה חוזרת מופיעים רק *, בדיוק כמו סיסמת ה-FTP",
  "המחרוזת ש-Quectel מנפיקה",
  "קריאת ה-token הנוכחי (חוזר מוסתר בכוכביות)",
  "קריאת שרת האיכון (היחידה הזו מגיעה עם www.queclocator.com:80)",
  "שינוי כתובת שרת האיכון",
  "שרת",
  "המבנה הוא «מארח:פורט». ערך היצרן של היחידה הזו הוא בדיוק זה, אז אל תיגע בו אלא אם Quectel אומרת אחרת",
  "קריאת פסק הזמן של השאילתה (היחידה הזו מגיעה עם 60 שניות)",
  "הגדרת פסק הזמן של השאילתה בשניות",
  "פסק זמן (שניות)",
  "טווח 10-120 (כפי ש-AT+QLBSCFG=? מחזירה בפועל), 60 מהיצרן ביחידה הזו",
  "קריאת המצב הסינכרוני / האסינכרוני (0 מהיצרן ביחידה הזו)",
  "מעבר בין סינכרוני לאסינכרוני",
  "0 = סינכרוני (הפקודה ממתינה לתוצאה); 1 = אסינכרוני (קודם חוזר OK, והתוצאה מגיעה בנפרד). ⚠ שתי המשמעויות האלה הוסקו משם הפריט — בלי token אי אפשר לאמת אותן ביחידה הזו",
  "קריאת סדר הפלט של קו הרוחב וקו האורך. ⚠ מגדירים עם המפתח באותיות קטנות latorder, אבל המודול מחזיר אותו בכתיב גמל latOrder",
  "קריאה האם התשובה נושאת חותם זמן (חוזר בשם withTime, 0 מהיצרן ביחידה הזו)",
  "קריאה האם תוצאת האיכון מתקנת את שעון המודול (חוזר בשם timeUpdate, 0 מהיצרן ביחידה הזו)",
  "ביצוע איכון רשת. ⚠ נדרשים token והקשר PDP פעיל, וזה צורך תעבורה. זו שיטת האיכון היחידה שעובדת בתוך מבנה — היא אינה משתמשת בלוויינים",
  "הצגת שבעת פריטי התצורה של QuecLocator עם הטווחים שלהם (ללא צריכת תעבורה, שום דבר לא יוצא לאוויר). נמדד ביחידה הזו ב-2026-08-07: ‏asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "הגדרת ה-token של QuecLocator. ⚠ יש לבקש את המחרוזת הזו מ-Quectel; היחידה הזו מגיעה בלעדיה, ובלעדיה AT+QLBS משיב תמיד 702 (נמדד ב-2026-08-07, גם token מומצא מחזיר 702). בקריאה חוזרת מופיעים רק *",
  "קריאת הערך הנוכחי של אותו פריט תצורה של QuecLocator (ללא צריכת תעבורה)",
  "הגדרת פריט תצורה של QuecLocator (ללא צריכת תעבורה; ההגדרה נשמרת במודול)",
  "ביצוע איכון רשת: המודול שולח לענן של QuecLocator את נקודות ה-Wi-Fi והתאים הסלולריים שהוא רואה ומקבל קואורדינטות. ⚠ נדרשים token והקשר PDP פעיל, וזה צורך תעבורה. זו שיטת האיכון היחידה שעובדת בתוך מבנה — בלי לוויינים, ולכן היא עובדת גם היכן ש-GNSS לא רואה כלום",
  "‏token של QuecLocator = {0}",
  "איכון הרשת נכשל — שגיאה {0}",
  "איכון הרשת נכשל — שגיאה {0}: {1}",
  "איכון הרשת הצליח, השדות שהוחזרו: {0}",
  "סינכרוני — הפקודה ממתינה לתוצאה; הסקה, ו-0 הוא אכן ערך היצרן של היחידה הזו",
  "אסינכרוני — קודם חוזר OK, והמיקום מגיע בנפרד; הסקה",
  "סדר ברירת המחדל — ערך היצרן שנמדד ביחידה הזו",
  "קו רוחב וקו אורך מוחלפים — הסקה",
  "התשובה בלי חותם זמן — ערך היצרן שנמדד ביחידה הזו",
  "התשובה עם חותם זמן — הסקה",
  "לא להשתמש בזמן של שירות האיכון לתיקון שעון המודול — ערך היצרן שנמדד ביחידה הזו",
  "להשתמש בזמן שמחזיר שירות האיכון לתיקון שעון המודול — הסקה",
  ". נמדד ב-2026-08-07: גם היעדר token וגם token לא תקין מחזירים את אותו הקוד; את ה-token מבקשים מ-Quectel והיחידה הזו מגיעה בלעדיו",
  "בקשת האיכון התקבלה",
  "(ל-QuecLocator אין מסמך רשמי ב-ref/ של הפרויקט הזה, ולכן משמעות הקוד הזה לא אומתה)",
  "(המודול מסתיר אותו בכוכביות בקריאה חוזרת; ללא token מוגדר, AT+QLBS משיב 702)",
  "(הסדר תלוי ב-AT+QLBSCFG=\"latorder\"; ללא token לא ניתן היה לבדוק זאת ביחידה הזו, ולכן התאמת השדות לא אומתה)"],
 'fa-IR': [
  "مکان‌یابی شبکه‌ای بدون ماهواره: ماژول نقطه‌های Wi-Fi و دکل‌های همراهی را که می‌بیند به ابر Quectel می‌فرستد و مختصات می‌گیرد، پس در فضای بسته هم کار می‌کند. ⚠ به توکنی نیاز دارد که Quectel صادر می‌کند؛ این دستگاه بدون توکن از کارخانه می‌آید و بی آن پاسخ همیشه ۷۰۲ است. ⚠ برای QuecLocator هیچ سند رسمی‌ای در ref/ این پروژه نیست، بنابراین آنچه در پی می‌آید تنها همان چیزی است که در ۲۰۲۶-۰۸-۰۷ اندازه‌گیری شد؛ هرچه گمانه‌زنی است نشانه‌گذاری شده",
  "فهرست کردن هفت زیرمورد پیکربندی و بازهٔ هر یک (بدون مصرف داده)",
  "تنظیم توکن QuecLocator (باید از Quectel درخواست شود)",
  "⚠ در این دستگاه از کارخانه خالی است؛ بی آن AT+QLBS همیشه ۷۰۲ برمی‌گرداند (اندازه‌گیری ۲۰۲۶-۰۸-۰۷ — رشتهٔ ساختگی هم ۷۰۲ می‌دهد). پس از تنظیم، هنگام خواندن تنها * دیده می‌شود، درست مانند گذرواژهٔ FTP",
  "رشته‌ای که Quectel صادر می‌کند",
  "خواندن توکن کنونی (پوشیده با * برمی‌گردد)",
  "خواندن کارساز مکان‌یابی (این دستگاه با www.queclocator.com:80 از کارخانه می‌آید)",
  "تغییر نشانی کارساز مکان‌یابی",
  "کارساز",
  "قالبش «میزبان:درگاه» است. مقدار کارخانه‌ای این دستگاه دقیقاً همین است، پس دست نزنید مگر Quectel جور دیگری بگوید",
  "خواندن مهلت پرس‌وجو (این دستگاه با ۶۰ ثانیه از کارخانه می‌آید)",
  "تنظیم مهلت پرس‌وجو بر حسب ثانیه",
  "مهلت (ثانیه)",
  "بازهٔ 10-120 (همان‌گونه که AT+QLBSCFG=? واقعاً برمی‌گرداند)، در این دستگاه ۶۰ از کارخانه",
  "خواندن حالت همگام / ناهمگام (در این دستگاه ۰ از کارخانه)",
  "جابه‌جایی میان همگام و ناهمگام",
  "۰ = همگام (فرمان تا رسیدن نتیجه منتظر می‌ماند)؛ ۱ = ناهمگام (نخست OK برمی‌گردد و نتیجه جداگانه می‌آید). ⚠ این دو معنا از نام زیرمورد استنباط شده‌اند —— بدون توکن در این دستگاه قابل راستی‌آزمایی نیستند",
  "خواندن ترتیب خروجی عرض و طول جغرافیایی. ⚠ با کلید حروف کوچک latorder تنظیم می‌شود، ولی ماژول آن را به شکل شتری latOrder بازمی‌خواند",
  "خواندن اینکه پاسخ زمان دارد یا نه (به نام withTime بازخوانده می‌شود، در این دستگاه ۰ از کارخانه)",
  "خواندن اینکه نتیجهٔ مکان‌یابی ساعت ماژول را تصحیح می‌کند یا نه (به نام timeUpdate بازخوانده می‌شود، در این دستگاه ۰ از کارخانه)",
  "اجرای مکان‌یابی شبکه‌ای. ⚠ به توکن و بافت PDP فعال نیاز دارد و داده مصرف می‌کند. این تنها روش مکان‌یابی است که در فضای بسته کار می‌کند —— چون از ماهواره استفاده نمی‌کند",
  "فهرست کردن هفت زیرمورد پیکربندی QuecLocator با بازهٔ هر یک (بدون مصرف داده، چیزی روی هوا نمی‌رود). در این دستگاه در ۲۰۲۶-۰۸-۰۷ اندازه‌گیری شد: ‏asynch(0,1) / timeout(10-120) / server / token / timeupdate(0,1) / withtime(0,1) / latorder(0,1)",
  "تنظیم توکن QuecLocator. ⚠ این رشته را باید از Quectel درخواست کرد؛ این دستگاه بی آن از کارخانه می‌آید و بی آن AT+QLBS همیشه ۷۰۲ برمی‌گرداند (اندازه‌گیری ۲۰۲۶-۰۸-۰۷، توکن ساختگی هم ۷۰۲ می‌دهد). هنگام خواندن تنها * دیده می‌شود",
  "خواندن مقدار کنونی آن زیرمورد QuecLocator (بدون مصرف داده)",
  "تنظیم یکی از زیرموردهای QuecLocator (بدون مصرف داده؛ تنظیم درون ماژول ذخیره می‌شود)",
  "اجرای مکان‌یابی شبکه‌ای: ماژول نقطه‌های Wi-Fi و دکل‌های همراهی را که می‌بیند به ابر QuecLocator می‌فرستد و مختصات می‌گیرد. ⚠ به توکن و بافت PDP فعال نیاز دارد و داده مصرف می‌کند. این تنها روش مکان‌یابی است که در فضای بسته کار می‌کند —— بی نیاز از ماهواره، پس هرجا GNSS چیزی نبیند این باز هم مکان را می‌یابد",
  "توکن QuecLocator = {0}",
  "مکان‌یابی شبکه‌ای ناکام ماند —— خطای {0}",
  "مکان‌یابی شبکه‌ای ناکام ماند —— خطای {0}: {1}",
  "مکان‌یابی شبکه‌ای کامیاب شد، میدان‌های بازگشتی: {0}",
  "همگام —— فرمان تا رسیدن نتیجه منتظر می‌ماند؛ گمانه‌زنی، و مقدار کارخانه‌ای این دستگاه هم همین ۰ است",
  "ناهمگام —— نخست OK برمی‌گردد و نتیجهٔ مکان‌یابی جداگانه می‌آید؛ گمانه‌زنی",
  "ترتیب پیش‌فرض —— مقدار کارخانه‌ای اندازه‌گیری‌شده در این دستگاه",
  "جابه‌جایی عرض و طول جغرافیایی —— گمانه‌زنی",
  "پاسخ بدون زمان —— مقدار کارخانه‌ای اندازه‌گیری‌شده در این دستگاه",
  "پاسخ همراه با زمان —— گمانه‌زنی",
  "از زمان سرویس مکان‌یابی برای تصحیح ساعت ماژول استفاده نشود —— مقدار کارخانه‌ای اندازه‌گیری‌شده در این دستگاه",
  "از زمانی که سرویس مکان‌یابی برمی‌گرداند برای تصحیح ساعت ماژول استفاده شود —— گمانه‌زنی",
  ". اندازه‌گیری ۲۰۲۶-۰۸-۰۷: هم نبودِ توکن و هم توکن نامعتبر همین کد را می‌دهند؛ توکن را باید از Quectel گرفت و این دستگاه بی آن از کارخانه می‌آید",
  "درخواست مکان‌یابی پذیرفته شد",
  "(برای QuecLocator سند رسمی‌ای در ref/ این پروژه نیست، پس معنای این کد تأیید نشده است)",
  "(ماژول هنگام بازخوانی آن را با * می‌پوشاند؛ اگر توکن تنظیم نشده باشد AT+QLBS پاسخ ۷۰۲ می‌دهد)",
  "(ترتیب تابع AT+QLBSCFG=\"latorder\" است؛ نبودِ توکن اجازهٔ آزمایش در این دستگاه را نداد، پس تناظر میدان‌ها تأیید نشده است)"],
}


def main():
    os.makedirs(OUT, exist_ok=True)
    for lang, vals in T.items():
        assert len(vals) == len(KEYS), '%s: %d != %d' % (lang, len(vals), len(KEYS))
        json.dump(dict(zip(KEYS, vals)),
                  io.open(os.path.join(OUT, lang + '.json'), 'w', encoding='utf-8'),
                  ensure_ascii=False, indent=1)
        print('  %-7s %d 條' % (lang, len(vals)))
    print('完成 %d 種語言' % len(T))


if __name__ == '__main__':
    main()
